// Code generated by ent, DO NOT EDIT.

package asset

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/pseudomuto/pacman/internal/types"
)

const (
	// Label holds the string label denoting the asset type in the database.
	Label = "asset"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldURI holds the string denoting the uri field in the database.
	FieldURI = "uri"
	// EdgeSumdbRecords holds the string denoting the sumdb_records edge name in mutations.
	EdgeSumdbRecords = "sumdb_records"
	// Table holds the table name of the asset in the database.
	Table = "assets"
	// SumdbRecordsTable is the table that holds the sumdb_records relation/edge. The primary key declared below.
	SumdbRecordsTable = "sum_db_record_assets"
	// SumdbRecordsInverseTable is the table name for the SumDBRecord entity.
	// It exists in this package in order to avoid circular dependency with the "sumdbrecord" package.
	SumdbRecordsInverseTable = "sum_db_records"
)

// Columns holds all SQL columns for asset fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldType,
	FieldURI,
}

var (
	// SumdbRecordsPrimaryKey and SumdbRecordsColumn2 are the table columns denoting the
	// primary key for the sumdb_records relation (M2M).
	SumdbRecordsPrimaryKey = []string{"sum_db_record_id", "asset_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// URIValidator is a validator for the "uri" field. It is called by the builders before save.
	URIValidator func(string) error
)

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type types.AssetType) error {
	switch _type.String() {
	case "text", "archive":
		return nil
	default:
		return fmt.Errorf("asset: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Asset queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByURI orders the results by the uri field.
func ByURI(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURI, opts...).ToFunc()
}

// BySumdbRecordsCount orders the results by sumdb_records count.
func BySumdbRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSumdbRecordsStep(), opts...)
	}
}

// BySumdbRecords orders the results by sumdb_records terms.
func BySumdbRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSumdbRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSumdbRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SumdbRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, SumdbRecordsTable, SumdbRecordsPrimaryKey...),
	)
}
