// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ArtifactsColumns holds the columns for the "artifacts" table.
	ArtifactsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 300},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"gomod"}},
	}
	// ArtifactsTable holds the schema information for the "artifacts" table.
	ArtifactsTable = &schema.Table{
		Name:       "artifacts",
		Columns:    ArtifactsColumns,
		PrimaryKey: []*schema.Column{ArtifactsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "artifact_created_at",
				Unique:  false,
				Columns: []*schema.Column{ArtifactsColumns[1]},
			},
			{
				Name:    "artifact_updated_at",
				Unique:  false,
				Columns: []*schema.Column{ArtifactsColumns[2]},
			},
		},
	}
	// ArtifactVersionsColumns holds the columns for the "artifact_versions" table.
	ArtifactVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "version", Type: field.TypeString, Size: 50},
		{Name: "uri", Type: field.TypeString, Size: 1000},
		{Name: "artifact_id", Type: field.TypeInt},
	}
	// ArtifactVersionsTable holds the schema information for the "artifact_versions" table.
	ArtifactVersionsTable = &schema.Table{
		Name:       "artifact_versions",
		Columns:    ArtifactVersionsColumns,
		PrimaryKey: []*schema.Column{ArtifactVersionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "artifact_versions_artifacts_versions",
				Columns:    []*schema.Column{ArtifactVersionsColumns[5]},
				RefColumns: []*schema.Column{ArtifactsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "artifactversion_created_at",
				Unique:  false,
				Columns: []*schema.Column{ArtifactVersionsColumns[1]},
			},
			{
				Name:    "artifactversion_updated_at",
				Unique:  false,
				Columns: []*schema.Column{ArtifactVersionsColumns[2]},
			},
			{
				Name:    "artifactversion_version_artifact_id",
				Unique:  true,
				Columns: []*schema.Column{ArtifactVersionsColumns[3], ArtifactVersionsColumns[5]},
			},
		},
	}
	// SumDbHashesColumns holds the columns for the "sum_db_hashes" table.
	SumDbHashesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "index", Type: field.TypeInt64},
		{Name: "hash", Type: field.TypeBytes},
		{Name: "tree_id", Type: field.TypeInt},
	}
	// SumDbHashesTable holds the schema information for the "sum_db_hashes" table.
	SumDbHashesTable = &schema.Table{
		Name:       "sum_db_hashes",
		Columns:    SumDbHashesColumns,
		PrimaryKey: []*schema.Column{SumDbHashesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sum_db_hashes_sum_db_trees_hashes",
				Columns:    []*schema.Column{SumDbHashesColumns[5]},
				RefColumns: []*schema.Column{SumDbTreesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "sumdbhash_created_at",
				Unique:  false,
				Columns: []*schema.Column{SumDbHashesColumns[1]},
			},
			{
				Name:    "sumdbhash_updated_at",
				Unique:  false,
				Columns: []*schema.Column{SumDbHashesColumns[2]},
			},
			{
				Name:    "sumdbhash_tree_id",
				Unique:  false,
				Columns: []*schema.Column{SumDbHashesColumns[5]},
			},
			{
				Name:    "sumdbhash_index_tree_id",
				Unique:  false,
				Columns: []*schema.Column{SumDbHashesColumns[3], SumDbHashesColumns[5]},
			},
		},
	}
	// SumDbRecordsColumns holds the columns for the "sum_db_records" table.
	SumDbRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "path", Type: field.TypeString, Size: 200},
		{Name: "version", Type: field.TypeString, Size: 20},
		{Name: "data", Type: field.TypeBytes},
		{Name: "tree_id", Type: field.TypeInt},
	}
	// SumDbRecordsTable holds the schema information for the "sum_db_records" table.
	SumDbRecordsTable = &schema.Table{
		Name:       "sum_db_records",
		Columns:    SumDbRecordsColumns,
		PrimaryKey: []*schema.Column{SumDbRecordsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sum_db_records_sum_db_trees_records",
				Columns:    []*schema.Column{SumDbRecordsColumns[6]},
				RefColumns: []*schema.Column{SumDbTreesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "sumdbrecord_created_at",
				Unique:  false,
				Columns: []*schema.Column{SumDbRecordsColumns[1]},
			},
			{
				Name:    "sumdbrecord_updated_at",
				Unique:  false,
				Columns: []*schema.Column{SumDbRecordsColumns[2]},
			},
			{
				Name:    "sumdbrecord_tree_id",
				Unique:  false,
				Columns: []*schema.Column{SumDbRecordsColumns[6]},
			},
			{
				Name:    "sumdbrecord_path_version_tree_id",
				Unique:  true,
				Columns: []*schema.Column{SumDbRecordsColumns[3], SumDbRecordsColumns[4], SumDbRecordsColumns[6]},
			},
		},
	}
	// SumDbTreesColumns holds the columns for the "sum_db_trees" table.
	SumDbTreesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 200},
		{Name: "signer_key", Type: field.TypeString, Size: 100},
		{Name: "verifier_key", Type: field.TypeString, Size: 100},
	}
	// SumDbTreesTable holds the schema information for the "sum_db_trees" table.
	SumDbTreesTable = &schema.Table{
		Name:       "sum_db_trees",
		Columns:    SumDbTreesColumns,
		PrimaryKey: []*schema.Column{SumDbTreesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sumdbtree_created_at",
				Unique:  false,
				Columns: []*schema.Column{SumDbTreesColumns[1]},
			},
			{
				Name:    "sumdbtree_updated_at",
				Unique:  false,
				Columns: []*schema.Column{SumDbTreesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ArtifactsTable,
		ArtifactVersionsTable,
		SumDbHashesTable,
		SumDbRecordsTable,
		SumDbTreesTable,
	}
)

func init() {
	ArtifactVersionsTable.ForeignKeys[0].RefTable = ArtifactsTable
	SumDbHashesTable.ForeignKeys[0].RefTable = SumDbTreesTable
	SumDbRecordsTable.ForeignKeys[0].RefTable = SumDbTreesTable
}
