// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/pseudomuto/pacman/internal/ent/archive"
	"github.com/pseudomuto/pacman/internal/ent/predicate"
	"github.com/pseudomuto/pacman/internal/ent/schema"
	"github.com/pseudomuto/pacman/internal/types"
)

// ArchiveUpdate is the builder for updating Archive entities.
type ArchiveUpdate struct {
	config
	hooks    []Hook
	mutation *ArchiveMutation
}

// Where appends a list predicates to the ArchiveUpdate builder.
func (_u *ArchiveUpdate) Where(ps ...predicate.Archive) *ArchiveUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ArchiveUpdate) SetUpdatedAt(v time.Time) *ArchiveUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetType sets the "type" field.
func (_u *ArchiveUpdate) SetType(v types.ArchiveType) *ArchiveUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ArchiveUpdate) SetNillableType(v *types.ArchiveType) *ArchiveUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetCoordinate sets the "coordinate" field.
func (_u *ArchiveUpdate) SetCoordinate(v string) *ArchiveUpdate {
	_u.mutation.SetCoordinate(v)
	return _u
}

// SetNillableCoordinate sets the "coordinate" field if the given value is not nil.
func (_u *ArchiveUpdate) SetNillableCoordinate(v *string) *ArchiveUpdate {
	if v != nil {
		_u.SetCoordinate(*v)
	}
	return _u
}

// SetAssets sets the "assets" field.
func (_u *ArchiveUpdate) SetAssets(v []schema.AssetURL) *ArchiveUpdate {
	_u.mutation.SetAssets(v)
	return _u
}

// AppendAssets appends value to the "assets" field.
func (_u *ArchiveUpdate) AppendAssets(v []schema.AssetURL) *ArchiveUpdate {
	_u.mutation.AppendAssets(v)
	return _u
}

// Mutation returns the ArchiveMutation object of the builder.
func (_u *ArchiveUpdate) Mutation() *ArchiveMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ArchiveUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArchiveUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ArchiveUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArchiveUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ArchiveUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := archive.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArchiveUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := archive.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Archive.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Coordinate(); ok {
		if err := archive.CoordinateValidator(v); err != nil {
			return &ValidationError{Name: "coordinate", err: fmt.Errorf(`ent: validator failed for field "Archive.coordinate": %w`, err)}
		}
	}
	return nil
}

func (_u *ArchiveUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(archive.Table, archive.Columns, sqlgraph.NewFieldSpec(archive.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(archive.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(archive.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Coordinate(); ok {
		_spec.SetField(archive.FieldCoordinate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Assets(); ok {
		_spec.SetField(archive.FieldAssets, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAssets(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, archive.FieldAssets, value)
		})
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{archive.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ArchiveUpdateOne is the builder for updating a single Archive entity.
type ArchiveUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArchiveMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ArchiveUpdateOne) SetUpdatedAt(v time.Time) *ArchiveUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetType sets the "type" field.
func (_u *ArchiveUpdateOne) SetType(v types.ArchiveType) *ArchiveUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ArchiveUpdateOne) SetNillableType(v *types.ArchiveType) *ArchiveUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetCoordinate sets the "coordinate" field.
func (_u *ArchiveUpdateOne) SetCoordinate(v string) *ArchiveUpdateOne {
	_u.mutation.SetCoordinate(v)
	return _u
}

// SetNillableCoordinate sets the "coordinate" field if the given value is not nil.
func (_u *ArchiveUpdateOne) SetNillableCoordinate(v *string) *ArchiveUpdateOne {
	if v != nil {
		_u.SetCoordinate(*v)
	}
	return _u
}

// SetAssets sets the "assets" field.
func (_u *ArchiveUpdateOne) SetAssets(v []schema.AssetURL) *ArchiveUpdateOne {
	_u.mutation.SetAssets(v)
	return _u
}

// AppendAssets appends value to the "assets" field.
func (_u *ArchiveUpdateOne) AppendAssets(v []schema.AssetURL) *ArchiveUpdateOne {
	_u.mutation.AppendAssets(v)
	return _u
}

// Mutation returns the ArchiveMutation object of the builder.
func (_u *ArchiveUpdateOne) Mutation() *ArchiveMutation {
	return _u.mutation
}

// Where appends a list predicates to the ArchiveUpdate builder.
func (_u *ArchiveUpdateOne) Where(ps ...predicate.Archive) *ArchiveUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ArchiveUpdateOne) Select(field string, fields ...string) *ArchiveUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Archive entity.
func (_u *ArchiveUpdateOne) Save(ctx context.Context) (*Archive, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArchiveUpdateOne) SaveX(ctx context.Context) *Archive {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ArchiveUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArchiveUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ArchiveUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := archive.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArchiveUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := archive.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Archive.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Coordinate(); ok {
		if err := archive.CoordinateValidator(v); err != nil {
			return &ValidationError{Name: "coordinate", err: fmt.Errorf(`ent: validator failed for field "Archive.coordinate": %w`, err)}
		}
	}
	return nil
}

func (_u *ArchiveUpdateOne) sqlSave(ctx context.Context) (_node *Archive, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(archive.Table, archive.Columns, sqlgraph.NewFieldSpec(archive.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Archive.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, archive.FieldID)
		for _, f := range fields {
			if !archive.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != archive.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(archive.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(archive.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Coordinate(); ok {
		_spec.SetField(archive.FieldCoordinate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Assets(); ok {
		_spec.SetField(archive.FieldAssets, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAssets(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, archive.FieldAssets, value)
		})
	}
	_node = &Archive{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{archive.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
