// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pseudomuto/pacman/internal/ent/artifactversion"
	"github.com/pseudomuto/pacman/internal/ent/predicate"
)

// ArtifactVersionUpdate is the builder for updating ArtifactVersion entities.
type ArtifactVersionUpdate struct {
	config
	hooks    []Hook
	mutation *ArtifactVersionMutation
}

// Where appends a list predicates to the ArtifactVersionUpdate builder.
func (_u *ArtifactVersionUpdate) Where(ps ...predicate.ArtifactVersion) *ArtifactVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ArtifactVersionUpdate) SetUpdatedAt(v time.Time) *ArtifactVersionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *ArtifactVersionUpdate) SetVersion(v string) *ArtifactVersionUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ArtifactVersionUpdate) SetNillableVersion(v *string) *ArtifactVersionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetURI sets the "uri" field.
func (_u *ArtifactVersionUpdate) SetURI(v string) *ArtifactVersionUpdate {
	_u.mutation.SetURI(v)
	return _u
}

// SetNillableURI sets the "uri" field if the given value is not nil.
func (_u *ArtifactVersionUpdate) SetNillableURI(v *string) *ArtifactVersionUpdate {
	if v != nil {
		_u.SetURI(*v)
	}
	return _u
}

// Mutation returns the ArtifactVersionMutation object of the builder.
func (_u *ArtifactVersionUpdate) Mutation() *ArtifactVersionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ArtifactVersionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArtifactVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ArtifactVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArtifactVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ArtifactVersionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := artifactversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArtifactVersionUpdate) check() error {
	if _u.mutation.ArtifactCleared() && len(_u.mutation.ArtifactIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ArtifactVersion.artifact"`)
	}
	return nil
}

func (_u *ArtifactVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(artifactversion.Table, artifactversion.Columns, sqlgraph.NewFieldSpec(artifactversion.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(artifactversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(artifactversion.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.URI(); ok {
		_spec.SetField(artifactversion.FieldURI, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{artifactversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ArtifactVersionUpdateOne is the builder for updating a single ArtifactVersion entity.
type ArtifactVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArtifactVersionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ArtifactVersionUpdateOne) SetUpdatedAt(v time.Time) *ArtifactVersionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *ArtifactVersionUpdateOne) SetVersion(v string) *ArtifactVersionUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ArtifactVersionUpdateOne) SetNillableVersion(v *string) *ArtifactVersionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetURI sets the "uri" field.
func (_u *ArtifactVersionUpdateOne) SetURI(v string) *ArtifactVersionUpdateOne {
	_u.mutation.SetURI(v)
	return _u
}

// SetNillableURI sets the "uri" field if the given value is not nil.
func (_u *ArtifactVersionUpdateOne) SetNillableURI(v *string) *ArtifactVersionUpdateOne {
	if v != nil {
		_u.SetURI(*v)
	}
	return _u
}

// Mutation returns the ArtifactVersionMutation object of the builder.
func (_u *ArtifactVersionUpdateOne) Mutation() *ArtifactVersionMutation {
	return _u.mutation
}

// Where appends a list predicates to the ArtifactVersionUpdate builder.
func (_u *ArtifactVersionUpdateOne) Where(ps ...predicate.ArtifactVersion) *ArtifactVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ArtifactVersionUpdateOne) Select(field string, fields ...string) *ArtifactVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ArtifactVersion entity.
func (_u *ArtifactVersionUpdateOne) Save(ctx context.Context) (*ArtifactVersion, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArtifactVersionUpdateOne) SaveX(ctx context.Context) *ArtifactVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ArtifactVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArtifactVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ArtifactVersionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := artifactversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArtifactVersionUpdateOne) check() error {
	if _u.mutation.ArtifactCleared() && len(_u.mutation.ArtifactIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ArtifactVersion.artifact"`)
	}
	return nil
}

func (_u *ArtifactVersionUpdateOne) sqlSave(ctx context.Context) (_node *ArtifactVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(artifactversion.Table, artifactversion.Columns, sqlgraph.NewFieldSpec(artifactversion.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ArtifactVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, artifactversion.FieldID)
		for _, f := range fields {
			if !artifactversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != artifactversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(artifactversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(artifactversion.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.URI(); ok {
		_spec.SetField(artifactversion.FieldURI, field.TypeString, value)
	}
	_node = &ArtifactVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{artifactversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
