// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pseudomuto/pacman/internal/ent/artifact"
	"github.com/pseudomuto/pacman/internal/ent/artifactversion"
)

// ArtifactVersionCreate is the builder for creating a ArtifactVersion entity.
type ArtifactVersionCreate struct {
	config
	mutation *ArtifactVersionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ArtifactVersionCreate) SetCreatedAt(v time.Time) *ArtifactVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ArtifactVersionCreate) SetNillableCreatedAt(v *time.Time) *ArtifactVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ArtifactVersionCreate) SetUpdatedAt(v time.Time) *ArtifactVersionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ArtifactVersionCreate) SetNillableUpdatedAt(v *time.Time) *ArtifactVersionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *ArtifactVersionCreate) SetVersion(v string) *ArtifactVersionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetURI sets the "uri" field.
func (_c *ArtifactVersionCreate) SetURI(v string) *ArtifactVersionCreate {
	_c.mutation.SetURI(v)
	return _c
}

// SetArtifactID sets the "artifact" edge to the Artifact entity by ID.
func (_c *ArtifactVersionCreate) SetArtifactID(id int) *ArtifactVersionCreate {
	_c.mutation.SetArtifactID(id)
	return _c
}

// SetArtifact sets the "artifact" edge to the Artifact entity.
func (_c *ArtifactVersionCreate) SetArtifact(v *Artifact) *ArtifactVersionCreate {
	return _c.SetArtifactID(v.ID)
}

// Mutation returns the ArtifactVersionMutation object of the builder.
func (_c *ArtifactVersionCreate) Mutation() *ArtifactVersionMutation {
	return _c.mutation
}

// Save creates the ArtifactVersion in the database.
func (_c *ArtifactVersionCreate) Save(ctx context.Context) (*ArtifactVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ArtifactVersionCreate) SaveX(ctx context.Context) *ArtifactVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArtifactVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArtifactVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ArtifactVersionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := artifactversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := artifactversion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ArtifactVersionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ArtifactVersion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ArtifactVersion.updated_at"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ArtifactVersion.version"`)}
	}
	if _, ok := _c.mutation.URI(); !ok {
		return &ValidationError{Name: "uri", err: errors.New(`ent: missing required field "ArtifactVersion.uri"`)}
	}
	if len(_c.mutation.ArtifactIDs()) == 0 {
		return &ValidationError{Name: "artifact", err: errors.New(`ent: missing required edge "ArtifactVersion.artifact"`)}
	}
	return nil
}

func (_c *ArtifactVersionCreate) sqlSave(ctx context.Context) (*ArtifactVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ArtifactVersionCreate) createSpec() (*ArtifactVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &ArtifactVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(artifactversion.Table, sqlgraph.NewFieldSpec(artifactversion.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(artifactversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(artifactversion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(artifactversion.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.URI(); ok {
		_spec.SetField(artifactversion.FieldURI, field.TypeString, value)
		_node.URI = value
	}
	if nodes := _c.mutation.ArtifactIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   artifactversion.ArtifactTable,
			Columns: []string{artifactversion.ArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artifact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.artifact_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ArtifactVersionCreateBulk is the builder for creating many ArtifactVersion entities in bulk.
type ArtifactVersionCreateBulk struct {
	config
	err      error
	builders []*ArtifactVersionCreate
}

// Save creates the ArtifactVersion entities in the database.
func (_c *ArtifactVersionCreateBulk) Save(ctx context.Context) ([]*ArtifactVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ArtifactVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArtifactVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ArtifactVersionCreateBulk) SaveX(ctx context.Context) []*ArtifactVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArtifactVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArtifactVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
