// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/pseudomuto/pacman/internal/ent/artifact"
	"github.com/pseudomuto/pacman/internal/ent/artifactversion"
)

// ArtifactVersion is the model entity for the ArtifactVersion schema.
type ArtifactVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// When this object was initially created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The last time this object was modified
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// URI holds the value of the "uri" field.
	URI string `json:"uri,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ArtifactVersionQuery when eager-loading is set.
	Edges        ArtifactVersionEdges `json:"edges"`
	artifact_id  *int
	selectValues sql.SelectValues
}

// ArtifactVersionEdges holds the relations/edges for other nodes in the graph.
type ArtifactVersionEdges struct {
	// The artifact this version belongs to
	Artifact *Artifact `json:"artifact,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ArtifactOrErr returns the Artifact value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ArtifactVersionEdges) ArtifactOrErr() (*Artifact, error) {
	if e.Artifact != nil {
		return e.Artifact, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: artifact.Label}
	}
	return nil, &NotLoadedError{edge: "artifact"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ArtifactVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case artifactversion.FieldID:
			values[i] = new(sql.NullInt64)
		case artifactversion.FieldVersion, artifactversion.FieldURI:
			values[i] = new(sql.NullString)
		case artifactversion.FieldCreatedAt, artifactversion.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case artifactversion.ForeignKeys[0]: // artifact_id
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ArtifactVersion fields.
func (_m *ArtifactVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case artifactversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case artifactversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case artifactversion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case artifactversion.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case artifactversion.FieldURI:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uri", values[i])
			} else if value.Valid {
				_m.URI = value.String
			}
		case artifactversion.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field artifact_id", value)
			} else if value.Valid {
				_m.artifact_id = new(int)
				*_m.artifact_id = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ArtifactVersion.
// This includes values selected through modifiers, order, etc.
func (_m *ArtifactVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryArtifact queries the "artifact" edge of the ArtifactVersion entity.
func (_m *ArtifactVersion) QueryArtifact() *ArtifactQuery {
	return NewArtifactVersionClient(_m.config).QueryArtifact(_m)
}

// Update returns a builder for updating this ArtifactVersion.
// Note that you need to call ArtifactVersion.Unwrap() before calling this method if this ArtifactVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ArtifactVersion) Update() *ArtifactVersionUpdateOne {
	return NewArtifactVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ArtifactVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ArtifactVersion) Unwrap() *ArtifactVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ArtifactVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ArtifactVersion) String() string {
	var builder strings.Builder
	builder.WriteString("ArtifactVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("uri=")
	builder.WriteString(_m.URI)
	builder.WriteByte(')')
	return builder.String()
}

// ArtifactVersions is a parsable slice of ArtifactVersion.
type ArtifactVersions []*ArtifactVersion
