// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pseudomuto/pacman/internal/ent/artifactversion"
	"github.com/pseudomuto/pacman/internal/ent/predicate"
)

// ArtifactVersionDelete is the builder for deleting a ArtifactVersion entity.
type ArtifactVersionDelete struct {
	config
	hooks    []Hook
	mutation *ArtifactVersionMutation
}

// Where appends a list predicates to the ArtifactVersionDelete builder.
func (_d *ArtifactVersionDelete) Where(ps ...predicate.ArtifactVersion) *ArtifactVersionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ArtifactVersionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ArtifactVersionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ArtifactVersionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(artifactversion.Table, sqlgraph.NewFieldSpec(artifactversion.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ArtifactVersionDeleteOne is the builder for deleting a single ArtifactVersion entity.
type ArtifactVersionDeleteOne struct {
	_d *ArtifactVersionDelete
}

// Where appends a list predicates to the ArtifactVersionDelete builder.
func (_d *ArtifactVersionDeleteOne) Where(ps ...predicate.ArtifactVersion) *ArtifactVersionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ArtifactVersionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{artifactversion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ArtifactVersionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
