// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pseudomuto/pacman/internal/ent/asset"
	"github.com/pseudomuto/pacman/internal/ent/predicate"
	"github.com/pseudomuto/pacman/internal/ent/sumdbrecord"
	"github.com/pseudomuto/pacman/internal/types"
)

// AssetUpdate is the builder for updating Asset entities.
type AssetUpdate struct {
	config
	hooks    []Hook
	mutation *AssetMutation
}

// Where appends a list predicates to the AssetUpdate builder.
func (_u *AssetUpdate) Where(ps ...predicate.Asset) *AssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AssetUpdate) SetUpdatedAt(v time.Time) *AssetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetType sets the "type" field.
func (_u *AssetUpdate) SetType(v types.AssetType) *AssetUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableType(v *types.AssetType) *AssetUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetURI sets the "uri" field.
func (_u *AssetUpdate) SetURI(v string) *AssetUpdate {
	_u.mutation.SetURI(v)
	return _u
}

// SetNillableURI sets the "uri" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableURI(v *string) *AssetUpdate {
	if v != nil {
		_u.SetURI(*v)
	}
	return _u
}

// AddSumdbRecordIDs adds the "sumdb_records" edge to the SumDBRecord entity by IDs.
func (_u *AssetUpdate) AddSumdbRecordIDs(ids ...int) *AssetUpdate {
	_u.mutation.AddSumdbRecordIDs(ids...)
	return _u
}

// AddSumdbRecords adds the "sumdb_records" edges to the SumDBRecord entity.
func (_u *AssetUpdate) AddSumdbRecords(v ...*SumDBRecord) *AssetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSumdbRecordIDs(ids...)
}

// Mutation returns the AssetMutation object of the builder.
func (_u *AssetUpdate) Mutation() *AssetMutation {
	return _u.mutation
}

// ClearSumdbRecords clears all "sumdb_records" edges to the SumDBRecord entity.
func (_u *AssetUpdate) ClearSumdbRecords() *AssetUpdate {
	_u.mutation.ClearSumdbRecords()
	return _u
}

// RemoveSumdbRecordIDs removes the "sumdb_records" edge to SumDBRecord entities by IDs.
func (_u *AssetUpdate) RemoveSumdbRecordIDs(ids ...int) *AssetUpdate {
	_u.mutation.RemoveSumdbRecordIDs(ids...)
	return _u
}

// RemoveSumdbRecords removes "sumdb_records" edges to SumDBRecord entities.
func (_u *AssetUpdate) RemoveSumdbRecords(v ...*SumDBRecord) *AssetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSumdbRecordIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AssetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AssetUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := asset.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssetUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := asset.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Asset.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URI(); ok {
		if err := asset.URIValidator(v); err != nil {
			return &ValidationError{Name: "uri", err: fmt.Errorf(`ent: validator failed for field "Asset.uri": %w`, err)}
		}
	}
	return nil
}

func (_u *AssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(asset.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(asset.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.URI(); ok {
		_spec.SetField(asset.FieldURI, field.TypeString, value)
	}
	if _u.mutation.SumdbRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   asset.SumdbRecordsTable,
			Columns: asset.SumdbRecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbrecord.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSumdbRecordsIDs(); len(nodes) > 0 && !_u.mutation.SumdbRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   asset.SumdbRecordsTable,
			Columns: asset.SumdbRecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SumdbRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   asset.SumdbRecordsTable,
			Columns: asset.SumdbRecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AssetUpdateOne is the builder for updating a single Asset entity.
type AssetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssetMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AssetUpdateOne) SetUpdatedAt(v time.Time) *AssetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetType sets the "type" field.
func (_u *AssetUpdateOne) SetType(v types.AssetType) *AssetUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableType(v *types.AssetType) *AssetUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetURI sets the "uri" field.
func (_u *AssetUpdateOne) SetURI(v string) *AssetUpdateOne {
	_u.mutation.SetURI(v)
	return _u
}

// SetNillableURI sets the "uri" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableURI(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetURI(*v)
	}
	return _u
}

// AddSumdbRecordIDs adds the "sumdb_records" edge to the SumDBRecord entity by IDs.
func (_u *AssetUpdateOne) AddSumdbRecordIDs(ids ...int) *AssetUpdateOne {
	_u.mutation.AddSumdbRecordIDs(ids...)
	return _u
}

// AddSumdbRecords adds the "sumdb_records" edges to the SumDBRecord entity.
func (_u *AssetUpdateOne) AddSumdbRecords(v ...*SumDBRecord) *AssetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSumdbRecordIDs(ids...)
}

// Mutation returns the AssetMutation object of the builder.
func (_u *AssetUpdateOne) Mutation() *AssetMutation {
	return _u.mutation
}

// ClearSumdbRecords clears all "sumdb_records" edges to the SumDBRecord entity.
func (_u *AssetUpdateOne) ClearSumdbRecords() *AssetUpdateOne {
	_u.mutation.ClearSumdbRecords()
	return _u
}

// RemoveSumdbRecordIDs removes the "sumdb_records" edge to SumDBRecord entities by IDs.
func (_u *AssetUpdateOne) RemoveSumdbRecordIDs(ids ...int) *AssetUpdateOne {
	_u.mutation.RemoveSumdbRecordIDs(ids...)
	return _u
}

// RemoveSumdbRecords removes "sumdb_records" edges to SumDBRecord entities.
func (_u *AssetUpdateOne) RemoveSumdbRecords(v ...*SumDBRecord) *AssetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSumdbRecordIDs(ids...)
}

// Where appends a list predicates to the AssetUpdate builder.
func (_u *AssetUpdateOne) Where(ps ...predicate.Asset) *AssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AssetUpdateOne) Select(field string, fields ...string) *AssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Asset entity.
func (_u *AssetUpdateOne) Save(ctx context.Context) (*Asset, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetUpdateOne) SaveX(ctx context.Context) *Asset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AssetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := asset.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssetUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := asset.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Asset.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URI(); ok {
		if err := asset.URIValidator(v); err != nil {
			return &ValidationError{Name: "uri", err: fmt.Errorf(`ent: validator failed for field "Asset.uri": %w`, err)}
		}
	}
	return nil
}

func (_u *AssetUpdateOne) sqlSave(ctx context.Context) (_node *Asset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Asset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, asset.FieldID)
		for _, f := range fields {
			if !asset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != asset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(asset.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(asset.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.URI(); ok {
		_spec.SetField(asset.FieldURI, field.TypeString, value)
	}
	if _u.mutation.SumdbRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   asset.SumdbRecordsTable,
			Columns: asset.SumdbRecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbrecord.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSumdbRecordsIDs(); len(nodes) > 0 && !_u.mutation.SumdbRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   asset.SumdbRecordsTable,
			Columns: asset.SumdbRecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SumdbRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   asset.SumdbRecordsTable,
			Columns: asset.SumdbRecordsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Asset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
