// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/pseudomuto/pacman/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/pseudomuto/pacman/internal/ent/archive"
	"github.com/pseudomuto/pacman/internal/ent/asset"
	"github.com/pseudomuto/pacman/internal/ent/sumdbhash"
	"github.com/pseudomuto/pacman/internal/ent/sumdbrecord"
	"github.com/pseudomuto/pacman/internal/ent/sumdbtree"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Archive is the client for interacting with the Archive builders.
	Archive *ArchiveClient
	// Asset is the client for interacting with the Asset builders.
	Asset *AssetClient
	// SumDBHash is the client for interacting with the SumDBHash builders.
	SumDBHash *SumDBHashClient
	// SumDBRecord is the client for interacting with the SumDBRecord builders.
	SumDBRecord *SumDBRecordClient
	// SumDBTree is the client for interacting with the SumDBTree builders.
	SumDBTree *SumDBTreeClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Archive = NewArchiveClient(c.config)
	c.Asset = NewAssetClient(c.config)
	c.SumDBHash = NewSumDBHashClient(c.config)
	c.SumDBRecord = NewSumDBRecordClient(c.config)
	c.SumDBTree = NewSumDBTreeClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Archive:     NewArchiveClient(cfg),
		Asset:       NewAssetClient(cfg),
		SumDBHash:   NewSumDBHashClient(cfg),
		SumDBRecord: NewSumDBRecordClient(cfg),
		SumDBTree:   NewSumDBTreeClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		Archive:     NewArchiveClient(cfg),
		Asset:       NewAssetClient(cfg),
		SumDBHash:   NewSumDBHashClient(cfg),
		SumDBRecord: NewSumDBRecordClient(cfg),
		SumDBTree:   NewSumDBTreeClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Archive.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Archive.Use(hooks...)
	c.Asset.Use(hooks...)
	c.SumDBHash.Use(hooks...)
	c.SumDBRecord.Use(hooks...)
	c.SumDBTree.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Archive.Intercept(interceptors...)
	c.Asset.Intercept(interceptors...)
	c.SumDBHash.Intercept(interceptors...)
	c.SumDBRecord.Intercept(interceptors...)
	c.SumDBTree.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ArchiveMutation:
		return c.Archive.mutate(ctx, m)
	case *AssetMutation:
		return c.Asset.mutate(ctx, m)
	case *SumDBHashMutation:
		return c.SumDBHash.mutate(ctx, m)
	case *SumDBRecordMutation:
		return c.SumDBRecord.mutate(ctx, m)
	case *SumDBTreeMutation:
		return c.SumDBTree.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ArchiveClient is a client for the Archive schema.
type ArchiveClient struct {
	config
}

// NewArchiveClient returns a client for the Archive from the given config.
func NewArchiveClient(c config) *ArchiveClient {
	return &ArchiveClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `archive.Hooks(f(g(h())))`.
func (c *ArchiveClient) Use(hooks ...Hook) {
	c.hooks.Archive = append(c.hooks.Archive, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `archive.Intercept(f(g(h())))`.
func (c *ArchiveClient) Intercept(interceptors ...Interceptor) {
	c.inters.Archive = append(c.inters.Archive, interceptors...)
}

// Create returns a builder for creating a Archive entity.
func (c *ArchiveClient) Create() *ArchiveCreate {
	mutation := newArchiveMutation(c.config, OpCreate)
	return &ArchiveCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Archive entities.
func (c *ArchiveClient) CreateBulk(builders ...*ArchiveCreate) *ArchiveCreateBulk {
	return &ArchiveCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ArchiveClient) MapCreateBulk(slice any, setFunc func(*ArchiveCreate, int)) *ArchiveCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ArchiveCreateBulk{err: fmt.Errorf("calling to ArchiveClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ArchiveCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ArchiveCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Archive.
func (c *ArchiveClient) Update() *ArchiveUpdate {
	mutation := newArchiveMutation(c.config, OpUpdate)
	return &ArchiveUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ArchiveClient) UpdateOne(_m *Archive) *ArchiveUpdateOne {
	mutation := newArchiveMutation(c.config, OpUpdateOne, withArchive(_m))
	return &ArchiveUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ArchiveClient) UpdateOneID(id int) *ArchiveUpdateOne {
	mutation := newArchiveMutation(c.config, OpUpdateOne, withArchiveID(id))
	return &ArchiveUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Archive.
func (c *ArchiveClient) Delete() *ArchiveDelete {
	mutation := newArchiveMutation(c.config, OpDelete)
	return &ArchiveDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ArchiveClient) DeleteOne(_m *Archive) *ArchiveDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ArchiveClient) DeleteOneID(id int) *ArchiveDeleteOne {
	builder := c.Delete().Where(archive.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ArchiveDeleteOne{builder}
}

// Query returns a query builder for Archive.
func (c *ArchiveClient) Query() *ArchiveQuery {
	return &ArchiveQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeArchive},
		inters: c.Interceptors(),
	}
}

// Get returns a Archive entity by its id.
func (c *ArchiveClient) Get(ctx context.Context, id int) (*Archive, error) {
	return c.Query().Where(archive.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ArchiveClient) GetX(ctx context.Context, id int) *Archive {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ArchiveClient) Hooks() []Hook {
	return c.hooks.Archive
}

// Interceptors returns the client interceptors.
func (c *ArchiveClient) Interceptors() []Interceptor {
	return c.inters.Archive
}

func (c *ArchiveClient) mutate(ctx context.Context, m *ArchiveMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ArchiveCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ArchiveUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ArchiveUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ArchiveDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Archive mutation op: %q", m.Op())
	}
}

// AssetClient is a client for the Asset schema.
type AssetClient struct {
	config
}

// NewAssetClient returns a client for the Asset from the given config.
func NewAssetClient(c config) *AssetClient {
	return &AssetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `asset.Hooks(f(g(h())))`.
func (c *AssetClient) Use(hooks ...Hook) {
	c.hooks.Asset = append(c.hooks.Asset, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `asset.Intercept(f(g(h())))`.
func (c *AssetClient) Intercept(interceptors ...Interceptor) {
	c.inters.Asset = append(c.inters.Asset, interceptors...)
}

// Create returns a builder for creating a Asset entity.
func (c *AssetClient) Create() *AssetCreate {
	mutation := newAssetMutation(c.config, OpCreate)
	return &AssetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Asset entities.
func (c *AssetClient) CreateBulk(builders ...*AssetCreate) *AssetCreateBulk {
	return &AssetCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AssetClient) MapCreateBulk(slice any, setFunc func(*AssetCreate, int)) *AssetCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AssetCreateBulk{err: fmt.Errorf("calling to AssetClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AssetCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AssetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Asset.
func (c *AssetClient) Update() *AssetUpdate {
	mutation := newAssetMutation(c.config, OpUpdate)
	return &AssetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AssetClient) UpdateOne(_m *Asset) *AssetUpdateOne {
	mutation := newAssetMutation(c.config, OpUpdateOne, withAsset(_m))
	return &AssetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AssetClient) UpdateOneID(id int) *AssetUpdateOne {
	mutation := newAssetMutation(c.config, OpUpdateOne, withAssetID(id))
	return &AssetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Asset.
func (c *AssetClient) Delete() *AssetDelete {
	mutation := newAssetMutation(c.config, OpDelete)
	return &AssetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AssetClient) DeleteOne(_m *Asset) *AssetDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AssetClient) DeleteOneID(id int) *AssetDeleteOne {
	builder := c.Delete().Where(asset.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AssetDeleteOne{builder}
}

// Query returns a query builder for Asset.
func (c *AssetClient) Query() *AssetQuery {
	return &AssetQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAsset},
		inters: c.Interceptors(),
	}
}

// Get returns a Asset entity by its id.
func (c *AssetClient) Get(ctx context.Context, id int) (*Asset, error) {
	return c.Query().Where(asset.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AssetClient) GetX(ctx context.Context, id int) *Asset {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySumdbRecords queries the sumdb_records edge of a Asset.
func (c *AssetClient) QuerySumdbRecords(_m *Asset) *SumDBRecordQuery {
	query := (&SumDBRecordClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(asset.Table, asset.FieldID, id),
			sqlgraph.To(sumdbrecord.Table, sumdbrecord.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, asset.SumdbRecordsTable, asset.SumdbRecordsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AssetClient) Hooks() []Hook {
	return c.hooks.Asset
}

// Interceptors returns the client interceptors.
func (c *AssetClient) Interceptors() []Interceptor {
	return c.inters.Asset
}

func (c *AssetClient) mutate(ctx context.Context, m *AssetMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AssetCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AssetUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AssetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AssetDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Asset mutation op: %q", m.Op())
	}
}

// SumDBHashClient is a client for the SumDBHash schema.
type SumDBHashClient struct {
	config
}

// NewSumDBHashClient returns a client for the SumDBHash from the given config.
func NewSumDBHashClient(c config) *SumDBHashClient {
	return &SumDBHashClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sumdbhash.Hooks(f(g(h())))`.
func (c *SumDBHashClient) Use(hooks ...Hook) {
	c.hooks.SumDBHash = append(c.hooks.SumDBHash, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sumdbhash.Intercept(f(g(h())))`.
func (c *SumDBHashClient) Intercept(interceptors ...Interceptor) {
	c.inters.SumDBHash = append(c.inters.SumDBHash, interceptors...)
}

// Create returns a builder for creating a SumDBHash entity.
func (c *SumDBHashClient) Create() *SumDBHashCreate {
	mutation := newSumDBHashMutation(c.config, OpCreate)
	return &SumDBHashCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SumDBHash entities.
func (c *SumDBHashClient) CreateBulk(builders ...*SumDBHashCreate) *SumDBHashCreateBulk {
	return &SumDBHashCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SumDBHashClient) MapCreateBulk(slice any, setFunc func(*SumDBHashCreate, int)) *SumDBHashCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SumDBHashCreateBulk{err: fmt.Errorf("calling to SumDBHashClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SumDBHashCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SumDBHashCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SumDBHash.
func (c *SumDBHashClient) Update() *SumDBHashUpdate {
	mutation := newSumDBHashMutation(c.config, OpUpdate)
	return &SumDBHashUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SumDBHashClient) UpdateOne(_m *SumDBHash) *SumDBHashUpdateOne {
	mutation := newSumDBHashMutation(c.config, OpUpdateOne, withSumDBHash(_m))
	return &SumDBHashUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SumDBHashClient) UpdateOneID(id int) *SumDBHashUpdateOne {
	mutation := newSumDBHashMutation(c.config, OpUpdateOne, withSumDBHashID(id))
	return &SumDBHashUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SumDBHash.
func (c *SumDBHashClient) Delete() *SumDBHashDelete {
	mutation := newSumDBHashMutation(c.config, OpDelete)
	return &SumDBHashDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SumDBHashClient) DeleteOne(_m *SumDBHash) *SumDBHashDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SumDBHashClient) DeleteOneID(id int) *SumDBHashDeleteOne {
	builder := c.Delete().Where(sumdbhash.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SumDBHashDeleteOne{builder}
}

// Query returns a query builder for SumDBHash.
func (c *SumDBHashClient) Query() *SumDBHashQuery {
	return &SumDBHashQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSumDBHash},
		inters: c.Interceptors(),
	}
}

// Get returns a SumDBHash entity by its id.
func (c *SumDBHashClient) Get(ctx context.Context, id int) (*SumDBHash, error) {
	return c.Query().Where(sumdbhash.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SumDBHashClient) GetX(ctx context.Context, id int) *SumDBHash {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTree queries the tree edge of a SumDBHash.
func (c *SumDBHashClient) QueryTree(_m *SumDBHash) *SumDBTreeQuery {
	query := (&SumDBTreeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sumdbhash.Table, sumdbhash.FieldID, id),
			sqlgraph.To(sumdbtree.Table, sumdbtree.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sumdbhash.TreeTable, sumdbhash.TreeColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SumDBHashClient) Hooks() []Hook {
	return c.hooks.SumDBHash
}

// Interceptors returns the client interceptors.
func (c *SumDBHashClient) Interceptors() []Interceptor {
	return c.inters.SumDBHash
}

func (c *SumDBHashClient) mutate(ctx context.Context, m *SumDBHashMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SumDBHashCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SumDBHashUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SumDBHashUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SumDBHashDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SumDBHash mutation op: %q", m.Op())
	}
}

// SumDBRecordClient is a client for the SumDBRecord schema.
type SumDBRecordClient struct {
	config
}

// NewSumDBRecordClient returns a client for the SumDBRecord from the given config.
func NewSumDBRecordClient(c config) *SumDBRecordClient {
	return &SumDBRecordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sumdbrecord.Hooks(f(g(h())))`.
func (c *SumDBRecordClient) Use(hooks ...Hook) {
	c.hooks.SumDBRecord = append(c.hooks.SumDBRecord, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sumdbrecord.Intercept(f(g(h())))`.
func (c *SumDBRecordClient) Intercept(interceptors ...Interceptor) {
	c.inters.SumDBRecord = append(c.inters.SumDBRecord, interceptors...)
}

// Create returns a builder for creating a SumDBRecord entity.
func (c *SumDBRecordClient) Create() *SumDBRecordCreate {
	mutation := newSumDBRecordMutation(c.config, OpCreate)
	return &SumDBRecordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SumDBRecord entities.
func (c *SumDBRecordClient) CreateBulk(builders ...*SumDBRecordCreate) *SumDBRecordCreateBulk {
	return &SumDBRecordCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SumDBRecordClient) MapCreateBulk(slice any, setFunc func(*SumDBRecordCreate, int)) *SumDBRecordCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SumDBRecordCreateBulk{err: fmt.Errorf("calling to SumDBRecordClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SumDBRecordCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SumDBRecordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SumDBRecord.
func (c *SumDBRecordClient) Update() *SumDBRecordUpdate {
	mutation := newSumDBRecordMutation(c.config, OpUpdate)
	return &SumDBRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SumDBRecordClient) UpdateOne(_m *SumDBRecord) *SumDBRecordUpdateOne {
	mutation := newSumDBRecordMutation(c.config, OpUpdateOne, withSumDBRecord(_m))
	return &SumDBRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SumDBRecordClient) UpdateOneID(id int) *SumDBRecordUpdateOne {
	mutation := newSumDBRecordMutation(c.config, OpUpdateOne, withSumDBRecordID(id))
	return &SumDBRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SumDBRecord.
func (c *SumDBRecordClient) Delete() *SumDBRecordDelete {
	mutation := newSumDBRecordMutation(c.config, OpDelete)
	return &SumDBRecordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SumDBRecordClient) DeleteOne(_m *SumDBRecord) *SumDBRecordDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SumDBRecordClient) DeleteOneID(id int) *SumDBRecordDeleteOne {
	builder := c.Delete().Where(sumdbrecord.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SumDBRecordDeleteOne{builder}
}

// Query returns a query builder for SumDBRecord.
func (c *SumDBRecordClient) Query() *SumDBRecordQuery {
	return &SumDBRecordQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSumDBRecord},
		inters: c.Interceptors(),
	}
}

// Get returns a SumDBRecord entity by its id.
func (c *SumDBRecordClient) Get(ctx context.Context, id int) (*SumDBRecord, error) {
	return c.Query().Where(sumdbrecord.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SumDBRecordClient) GetX(ctx context.Context, id int) *SumDBRecord {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAssets queries the assets edge of a SumDBRecord.
func (c *SumDBRecordClient) QueryAssets(_m *SumDBRecord) *AssetQuery {
	query := (&AssetClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sumdbrecord.Table, sumdbrecord.FieldID, id),
			sqlgraph.To(asset.Table, asset.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, sumdbrecord.AssetsTable, sumdbrecord.AssetsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTree queries the tree edge of a SumDBRecord.
func (c *SumDBRecordClient) QueryTree(_m *SumDBRecord) *SumDBTreeQuery {
	query := (&SumDBTreeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sumdbrecord.Table, sumdbrecord.FieldID, id),
			sqlgraph.To(sumdbtree.Table, sumdbtree.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sumdbrecord.TreeTable, sumdbrecord.TreeColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SumDBRecordClient) Hooks() []Hook {
	return c.hooks.SumDBRecord
}

// Interceptors returns the client interceptors.
func (c *SumDBRecordClient) Interceptors() []Interceptor {
	return c.inters.SumDBRecord
}

func (c *SumDBRecordClient) mutate(ctx context.Context, m *SumDBRecordMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SumDBRecordCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SumDBRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SumDBRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SumDBRecordDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SumDBRecord mutation op: %q", m.Op())
	}
}

// SumDBTreeClient is a client for the SumDBTree schema.
type SumDBTreeClient struct {
	config
}

// NewSumDBTreeClient returns a client for the SumDBTree from the given config.
func NewSumDBTreeClient(c config) *SumDBTreeClient {
	return &SumDBTreeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sumdbtree.Hooks(f(g(h())))`.
func (c *SumDBTreeClient) Use(hooks ...Hook) {
	c.hooks.SumDBTree = append(c.hooks.SumDBTree, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sumdbtree.Intercept(f(g(h())))`.
func (c *SumDBTreeClient) Intercept(interceptors ...Interceptor) {
	c.inters.SumDBTree = append(c.inters.SumDBTree, interceptors...)
}

// Create returns a builder for creating a SumDBTree entity.
func (c *SumDBTreeClient) Create() *SumDBTreeCreate {
	mutation := newSumDBTreeMutation(c.config, OpCreate)
	return &SumDBTreeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SumDBTree entities.
func (c *SumDBTreeClient) CreateBulk(builders ...*SumDBTreeCreate) *SumDBTreeCreateBulk {
	return &SumDBTreeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SumDBTreeClient) MapCreateBulk(slice any, setFunc func(*SumDBTreeCreate, int)) *SumDBTreeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SumDBTreeCreateBulk{err: fmt.Errorf("calling to SumDBTreeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SumDBTreeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SumDBTreeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SumDBTree.
func (c *SumDBTreeClient) Update() *SumDBTreeUpdate {
	mutation := newSumDBTreeMutation(c.config, OpUpdate)
	return &SumDBTreeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SumDBTreeClient) UpdateOne(_m *SumDBTree) *SumDBTreeUpdateOne {
	mutation := newSumDBTreeMutation(c.config, OpUpdateOne, withSumDBTree(_m))
	return &SumDBTreeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SumDBTreeClient) UpdateOneID(id int) *SumDBTreeUpdateOne {
	mutation := newSumDBTreeMutation(c.config, OpUpdateOne, withSumDBTreeID(id))
	return &SumDBTreeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SumDBTree.
func (c *SumDBTreeClient) Delete() *SumDBTreeDelete {
	mutation := newSumDBTreeMutation(c.config, OpDelete)
	return &SumDBTreeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SumDBTreeClient) DeleteOne(_m *SumDBTree) *SumDBTreeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SumDBTreeClient) DeleteOneID(id int) *SumDBTreeDeleteOne {
	builder := c.Delete().Where(sumdbtree.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SumDBTreeDeleteOne{builder}
}

// Query returns a query builder for SumDBTree.
func (c *SumDBTreeClient) Query() *SumDBTreeQuery {
	return &SumDBTreeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSumDBTree},
		inters: c.Interceptors(),
	}
}

// Get returns a SumDBTree entity by its id.
func (c *SumDBTreeClient) Get(ctx context.Context, id int) (*SumDBTree, error) {
	return c.Query().Where(sumdbtree.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SumDBTreeClient) GetX(ctx context.Context, id int) *SumDBTree {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryHashes queries the hashes edge of a SumDBTree.
func (c *SumDBTreeClient) QueryHashes(_m *SumDBTree) *SumDBHashQuery {
	query := (&SumDBHashClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sumdbtree.Table, sumdbtree.FieldID, id),
			sqlgraph.To(sumdbhash.Table, sumdbhash.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, sumdbtree.HashesTable, sumdbtree.HashesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRecords queries the records edge of a SumDBTree.
func (c *SumDBTreeClient) QueryRecords(_m *SumDBTree) *SumDBRecordQuery {
	query := (&SumDBRecordClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sumdbtree.Table, sumdbtree.FieldID, id),
			sqlgraph.To(sumdbrecord.Table, sumdbrecord.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, sumdbtree.RecordsTable, sumdbtree.RecordsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SumDBTreeClient) Hooks() []Hook {
	return c.hooks.SumDBTree
}

// Interceptors returns the client interceptors.
func (c *SumDBTreeClient) Interceptors() []Interceptor {
	return c.inters.SumDBTree
}

func (c *SumDBTreeClient) mutate(ctx context.Context, m *SumDBTreeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SumDBTreeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SumDBTreeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SumDBTreeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SumDBTreeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SumDBTree mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Archive, Asset, SumDBHash, SumDBRecord, SumDBTree []ent.Hook
	}
	inters struct {
		Archive, Asset, SumDBHash, SumDBRecord, SumDBTree []ent.Interceptor
	}
)
