// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/pseudomuto/pacman/internal/ent/artifact"
	"github.com/pseudomuto/pacman/internal/ent/artifactversion"
	"github.com/pseudomuto/pacman/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	artifactMixin := schema.Artifact{}.Mixin()
	artifactMixinFields0 := artifactMixin[0].Fields()
	_ = artifactMixinFields0
	artifactFields := schema.Artifact{}.Fields()
	_ = artifactFields
	// artifactDescCreatedAt is the schema descriptor for created_at field.
	artifactDescCreatedAt := artifactMixinFields0[0].Descriptor()
	// artifact.DefaultCreatedAt holds the default value on creation for the created_at field.
	artifact.DefaultCreatedAt = artifactDescCreatedAt.Default.(func() time.Time)
	// artifactDescUpdatedAt is the schema descriptor for updated_at field.
	artifactDescUpdatedAt := artifactMixinFields0[1].Descriptor()
	// artifact.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	artifact.DefaultUpdatedAt = artifactDescUpdatedAt.Default.(func() time.Time)
	// artifact.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	artifact.UpdateDefaultUpdatedAt = artifactDescUpdatedAt.UpdateDefault.(func() time.Time)
	// artifactDescName is the schema descriptor for name field.
	artifactDescName := artifactFields[0].Descriptor()
	// artifact.NameValidator is a validator for the "name" field. It is called by the builders before save.
	artifact.NameValidator = artifactDescName.Validators[0].(func(string) error)
	artifactversionMixin := schema.ArtifactVersion{}.Mixin()
	artifactversionMixinFields0 := artifactversionMixin[0].Fields()
	_ = artifactversionMixinFields0
	artifactversionFields := schema.ArtifactVersion{}.Fields()
	_ = artifactversionFields
	// artifactversionDescCreatedAt is the schema descriptor for created_at field.
	artifactversionDescCreatedAt := artifactversionMixinFields0[0].Descriptor()
	// artifactversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	artifactversion.DefaultCreatedAt = artifactversionDescCreatedAt.Default.(func() time.Time)
	// artifactversionDescUpdatedAt is the schema descriptor for updated_at field.
	artifactversionDescUpdatedAt := artifactversionMixinFields0[1].Descriptor()
	// artifactversion.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	artifactversion.DefaultUpdatedAt = artifactversionDescUpdatedAt.Default.(func() time.Time)
	// artifactversion.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	artifactversion.UpdateDefaultUpdatedAt = artifactversionDescUpdatedAt.UpdateDefault.(func() time.Time)
}
