// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pseudomuto/pacman/internal/crypto"
	"github.com/pseudomuto/pacman/internal/ent/predicate"
	"github.com/pseudomuto/pacman/internal/ent/sumdbhash"
	"github.com/pseudomuto/pacman/internal/ent/sumdbrecord"
	"github.com/pseudomuto/pacman/internal/ent/sumdbtree"
)

// SumDBTreeUpdate is the builder for updating SumDBTree entities.
type SumDBTreeUpdate struct {
	config
	hooks    []Hook
	mutation *SumDBTreeMutation
}

// Where appends a list predicates to the SumDBTreeUpdate builder.
func (_u *SumDBTreeUpdate) Where(ps ...predicate.SumDBTree) *SumDBTreeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SumDBTreeUpdate) SetUpdatedAt(v time.Time) *SumDBTreeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SumDBTreeUpdate) SetName(v string) *SumDBTreeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SumDBTreeUpdate) SetNillableName(v *string) *SumDBTreeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSignerKey sets the "signer_key" field.
func (_u *SumDBTreeUpdate) SetSignerKey(v crypto.Secret) *SumDBTreeUpdate {
	_u.mutation.SetSignerKey(v)
	return _u
}

// SetNillableSignerKey sets the "signer_key" field if the given value is not nil.
func (_u *SumDBTreeUpdate) SetNillableSignerKey(v *crypto.Secret) *SumDBTreeUpdate {
	if v != nil {
		_u.SetSignerKey(*v)
	}
	return _u
}

// SetVerifierKey sets the "verifier_key" field.
func (_u *SumDBTreeUpdate) SetVerifierKey(v string) *SumDBTreeUpdate {
	_u.mutation.SetVerifierKey(v)
	return _u
}

// SetNillableVerifierKey sets the "verifier_key" field if the given value is not nil.
func (_u *SumDBTreeUpdate) SetNillableVerifierKey(v *string) *SumDBTreeUpdate {
	if v != nil {
		_u.SetVerifierKey(*v)
	}
	return _u
}

// AddHashIDs adds the "hashes" edge to the SumDBHash entity by IDs.
func (_u *SumDBTreeUpdate) AddHashIDs(ids ...int) *SumDBTreeUpdate {
	_u.mutation.AddHashIDs(ids...)
	return _u
}

// AddHashes adds the "hashes" edges to the SumDBHash entity.
func (_u *SumDBTreeUpdate) AddHashes(v ...*SumDBHash) *SumDBTreeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHashIDs(ids...)
}

// AddRecordIDs adds the "records" edge to the SumDBRecord entity by IDs.
func (_u *SumDBTreeUpdate) AddRecordIDs(ids ...int) *SumDBTreeUpdate {
	_u.mutation.AddRecordIDs(ids...)
	return _u
}

// AddRecords adds the "records" edges to the SumDBRecord entity.
func (_u *SumDBTreeUpdate) AddRecords(v ...*SumDBRecord) *SumDBTreeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecordIDs(ids...)
}

// Mutation returns the SumDBTreeMutation object of the builder.
func (_u *SumDBTreeUpdate) Mutation() *SumDBTreeMutation {
	return _u.mutation
}

// ClearHashes clears all "hashes" edges to the SumDBHash entity.
func (_u *SumDBTreeUpdate) ClearHashes() *SumDBTreeUpdate {
	_u.mutation.ClearHashes()
	return _u
}

// RemoveHashIDs removes the "hashes" edge to SumDBHash entities by IDs.
func (_u *SumDBTreeUpdate) RemoveHashIDs(ids ...int) *SumDBTreeUpdate {
	_u.mutation.RemoveHashIDs(ids...)
	return _u
}

// RemoveHashes removes "hashes" edges to SumDBHash entities.
func (_u *SumDBTreeUpdate) RemoveHashes(v ...*SumDBHash) *SumDBTreeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHashIDs(ids...)
}

// ClearRecords clears all "records" edges to the SumDBRecord entity.
func (_u *SumDBTreeUpdate) ClearRecords() *SumDBTreeUpdate {
	_u.mutation.ClearRecords()
	return _u
}

// RemoveRecordIDs removes the "records" edge to SumDBRecord entities by IDs.
func (_u *SumDBTreeUpdate) RemoveRecordIDs(ids ...int) *SumDBTreeUpdate {
	_u.mutation.RemoveRecordIDs(ids...)
	return _u
}

// RemoveRecords removes "records" edges to SumDBRecord entities.
func (_u *SumDBTreeUpdate) RemoveRecords(v ...*SumDBRecord) *SumDBTreeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecordIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SumDBTreeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SumDBTreeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SumDBTreeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SumDBTreeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SumDBTreeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sumdbtree.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SumDBTreeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := sumdbtree.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SumDBTree.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SignerKey(); ok {
		if err := sumdbtree.SignerKeyValidator(string(v)); err != nil {
			return &ValidationError{Name: "signer_key", err: fmt.Errorf(`ent: validator failed for field "SumDBTree.signer_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VerifierKey(); ok {
		if err := sumdbtree.VerifierKeyValidator(v); err != nil {
			return &ValidationError{Name: "verifier_key", err: fmt.Errorf(`ent: validator failed for field "SumDBTree.verifier_key": %w`, err)}
		}
	}
	return nil
}

func (_u *SumDBTreeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sumdbtree.Table, sumdbtree.Columns, sqlgraph.NewFieldSpec(sumdbtree.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sumdbtree.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sumdbtree.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SignerKey(); ok {
		_spec.SetField(sumdbtree.FieldSignerKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerifierKey(); ok {
		_spec.SetField(sumdbtree.FieldVerifierKey, field.TypeString, value)
	}
	if _u.mutation.HashesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sumdbtree.HashesTable,
			Columns: []string{sumdbtree.HashesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbhash.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHashesIDs(); len(nodes) > 0 && !_u.mutation.HashesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sumdbtree.HashesTable,
			Columns: []string{sumdbtree.HashesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbhash.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HashesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sumdbtree.HashesTable,
			Columns: []string{sumdbtree.HashesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbhash.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sumdbtree.RecordsTable,
			Columns: []string{sumdbtree.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbrecord.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecordsIDs(); len(nodes) > 0 && !_u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sumdbtree.RecordsTable,
			Columns: []string{sumdbtree.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sumdbtree.RecordsTable,
			Columns: []string{sumdbtree.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sumdbtree.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SumDBTreeUpdateOne is the builder for updating a single SumDBTree entity.
type SumDBTreeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SumDBTreeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SumDBTreeUpdateOne) SetUpdatedAt(v time.Time) *SumDBTreeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SumDBTreeUpdateOne) SetName(v string) *SumDBTreeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SumDBTreeUpdateOne) SetNillableName(v *string) *SumDBTreeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSignerKey sets the "signer_key" field.
func (_u *SumDBTreeUpdateOne) SetSignerKey(v crypto.Secret) *SumDBTreeUpdateOne {
	_u.mutation.SetSignerKey(v)
	return _u
}

// SetNillableSignerKey sets the "signer_key" field if the given value is not nil.
func (_u *SumDBTreeUpdateOne) SetNillableSignerKey(v *crypto.Secret) *SumDBTreeUpdateOne {
	if v != nil {
		_u.SetSignerKey(*v)
	}
	return _u
}

// SetVerifierKey sets the "verifier_key" field.
func (_u *SumDBTreeUpdateOne) SetVerifierKey(v string) *SumDBTreeUpdateOne {
	_u.mutation.SetVerifierKey(v)
	return _u
}

// SetNillableVerifierKey sets the "verifier_key" field if the given value is not nil.
func (_u *SumDBTreeUpdateOne) SetNillableVerifierKey(v *string) *SumDBTreeUpdateOne {
	if v != nil {
		_u.SetVerifierKey(*v)
	}
	return _u
}

// AddHashIDs adds the "hashes" edge to the SumDBHash entity by IDs.
func (_u *SumDBTreeUpdateOne) AddHashIDs(ids ...int) *SumDBTreeUpdateOne {
	_u.mutation.AddHashIDs(ids...)
	return _u
}

// AddHashes adds the "hashes" edges to the SumDBHash entity.
func (_u *SumDBTreeUpdateOne) AddHashes(v ...*SumDBHash) *SumDBTreeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHashIDs(ids...)
}

// AddRecordIDs adds the "records" edge to the SumDBRecord entity by IDs.
func (_u *SumDBTreeUpdateOne) AddRecordIDs(ids ...int) *SumDBTreeUpdateOne {
	_u.mutation.AddRecordIDs(ids...)
	return _u
}

// AddRecords adds the "records" edges to the SumDBRecord entity.
func (_u *SumDBTreeUpdateOne) AddRecords(v ...*SumDBRecord) *SumDBTreeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecordIDs(ids...)
}

// Mutation returns the SumDBTreeMutation object of the builder.
func (_u *SumDBTreeUpdateOne) Mutation() *SumDBTreeMutation {
	return _u.mutation
}

// ClearHashes clears all "hashes" edges to the SumDBHash entity.
func (_u *SumDBTreeUpdateOne) ClearHashes() *SumDBTreeUpdateOne {
	_u.mutation.ClearHashes()
	return _u
}

// RemoveHashIDs removes the "hashes" edge to SumDBHash entities by IDs.
func (_u *SumDBTreeUpdateOne) RemoveHashIDs(ids ...int) *SumDBTreeUpdateOne {
	_u.mutation.RemoveHashIDs(ids...)
	return _u
}

// RemoveHashes removes "hashes" edges to SumDBHash entities.
func (_u *SumDBTreeUpdateOne) RemoveHashes(v ...*SumDBHash) *SumDBTreeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHashIDs(ids...)
}

// ClearRecords clears all "records" edges to the SumDBRecord entity.
func (_u *SumDBTreeUpdateOne) ClearRecords() *SumDBTreeUpdateOne {
	_u.mutation.ClearRecords()
	return _u
}

// RemoveRecordIDs removes the "records" edge to SumDBRecord entities by IDs.
func (_u *SumDBTreeUpdateOne) RemoveRecordIDs(ids ...int) *SumDBTreeUpdateOne {
	_u.mutation.RemoveRecordIDs(ids...)
	return _u
}

// RemoveRecords removes "records" edges to SumDBRecord entities.
func (_u *SumDBTreeUpdateOne) RemoveRecords(v ...*SumDBRecord) *SumDBTreeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecordIDs(ids...)
}

// Where appends a list predicates to the SumDBTreeUpdate builder.
func (_u *SumDBTreeUpdateOne) Where(ps ...predicate.SumDBTree) *SumDBTreeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SumDBTreeUpdateOne) Select(field string, fields ...string) *SumDBTreeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SumDBTree entity.
func (_u *SumDBTreeUpdateOne) Save(ctx context.Context) (*SumDBTree, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SumDBTreeUpdateOne) SaveX(ctx context.Context) *SumDBTree {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SumDBTreeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SumDBTreeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SumDBTreeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sumdbtree.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SumDBTreeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := sumdbtree.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SumDBTree.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SignerKey(); ok {
		if err := sumdbtree.SignerKeyValidator(string(v)); err != nil {
			return &ValidationError{Name: "signer_key", err: fmt.Errorf(`ent: validator failed for field "SumDBTree.signer_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VerifierKey(); ok {
		if err := sumdbtree.VerifierKeyValidator(v); err != nil {
			return &ValidationError{Name: "verifier_key", err: fmt.Errorf(`ent: validator failed for field "SumDBTree.verifier_key": %w`, err)}
		}
	}
	return nil
}

func (_u *SumDBTreeUpdateOne) sqlSave(ctx context.Context) (_node *SumDBTree, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sumdbtree.Table, sumdbtree.Columns, sqlgraph.NewFieldSpec(sumdbtree.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SumDBTree.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sumdbtree.FieldID)
		for _, f := range fields {
			if !sumdbtree.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sumdbtree.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sumdbtree.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sumdbtree.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SignerKey(); ok {
		_spec.SetField(sumdbtree.FieldSignerKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerifierKey(); ok {
		_spec.SetField(sumdbtree.FieldVerifierKey, field.TypeString, value)
	}
	if _u.mutation.HashesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sumdbtree.HashesTable,
			Columns: []string{sumdbtree.HashesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbhash.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHashesIDs(); len(nodes) > 0 && !_u.mutation.HashesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sumdbtree.HashesTable,
			Columns: []string{sumdbtree.HashesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbhash.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HashesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sumdbtree.HashesTable,
			Columns: []string{sumdbtree.HashesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbhash.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sumdbtree.RecordsTable,
			Columns: []string{sumdbtree.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbrecord.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecordsIDs(); len(nodes) > 0 && !_u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sumdbtree.RecordsTable,
			Columns: []string{sumdbtree.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sumdbtree.RecordsTable,
			Columns: []string{sumdbtree.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SumDBTree{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sumdbtree.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
