// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pseudomuto/pacman/internal/ent/asset"
	"github.com/pseudomuto/pacman/internal/ent/predicate"
	"github.com/pseudomuto/pacman/internal/ent/sumdbrecord"
)

// SumDBRecordUpdate is the builder for updating SumDBRecord entities.
type SumDBRecordUpdate struct {
	config
	hooks    []Hook
	mutation *SumDBRecordMutation
}

// Where appends a list predicates to the SumDBRecordUpdate builder.
func (_u *SumDBRecordUpdate) Where(ps ...predicate.SumDBRecord) *SumDBRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SumDBRecordUpdate) SetUpdatedAt(v time.Time) *SumDBRecordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRecordID sets the "record_id" field.
func (_u *SumDBRecordUpdate) SetRecordID(v int64) *SumDBRecordUpdate {
	_u.mutation.ResetRecordID()
	_u.mutation.SetRecordID(v)
	return _u
}

// SetNillableRecordID sets the "record_id" field if the given value is not nil.
func (_u *SumDBRecordUpdate) SetNillableRecordID(v *int64) *SumDBRecordUpdate {
	if v != nil {
		_u.SetRecordID(*v)
	}
	return _u
}

// AddRecordID adds value to the "record_id" field.
func (_u *SumDBRecordUpdate) AddRecordID(v int64) *SumDBRecordUpdate {
	_u.mutation.AddRecordID(v)
	return _u
}

// SetPath sets the "path" field.
func (_u *SumDBRecordUpdate) SetPath(v string) *SumDBRecordUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *SumDBRecordUpdate) SetNillablePath(v *string) *SumDBRecordUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *SumDBRecordUpdate) SetVersion(v string) *SumDBRecordUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SumDBRecordUpdate) SetNillableVersion(v *string) *SumDBRecordUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetData sets the "data" field.
func (_u *SumDBRecordUpdate) SetData(v []byte) *SumDBRecordUpdate {
	_u.mutation.SetData(v)
	return _u
}

// AddAssetIDs adds the "assets" edge to the Asset entity by IDs.
func (_u *SumDBRecordUpdate) AddAssetIDs(ids ...int) *SumDBRecordUpdate {
	_u.mutation.AddAssetIDs(ids...)
	return _u
}

// AddAssets adds the "assets" edges to the Asset entity.
func (_u *SumDBRecordUpdate) AddAssets(v ...*Asset) *SumDBRecordUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssetIDs(ids...)
}

// Mutation returns the SumDBRecordMutation object of the builder.
func (_u *SumDBRecordUpdate) Mutation() *SumDBRecordMutation {
	return _u.mutation
}

// ClearAssets clears all "assets" edges to the Asset entity.
func (_u *SumDBRecordUpdate) ClearAssets() *SumDBRecordUpdate {
	_u.mutation.ClearAssets()
	return _u
}

// RemoveAssetIDs removes the "assets" edge to Asset entities by IDs.
func (_u *SumDBRecordUpdate) RemoveAssetIDs(ids ...int) *SumDBRecordUpdate {
	_u.mutation.RemoveAssetIDs(ids...)
	return _u
}

// RemoveAssets removes "assets" edges to Asset entities.
func (_u *SumDBRecordUpdate) RemoveAssets(v ...*Asset) *SumDBRecordUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssetIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SumDBRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SumDBRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SumDBRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SumDBRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SumDBRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sumdbrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SumDBRecordUpdate) check() error {
	if v, ok := _u.mutation.Path(); ok {
		if err := sumdbrecord.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "SumDBRecord.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := sumdbrecord.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "SumDBRecord.version": %w`, err)}
		}
	}
	if _u.mutation.TreeCleared() && len(_u.mutation.TreeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SumDBRecord.tree"`)
	}
	return nil
}

func (_u *SumDBRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sumdbrecord.Table, sumdbrecord.Columns, sqlgraph.NewFieldSpec(sumdbrecord.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sumdbrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RecordID(); ok {
		_spec.SetField(sumdbrecord.FieldRecordID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecordID(); ok {
		_spec.AddField(sumdbrecord.FieldRecordID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(sumdbrecord.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(sumdbrecord.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(sumdbrecord.FieldData, field.TypeBytes, value)
	}
	if _u.mutation.AssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   sumdbrecord.AssetsTable,
			Columns: sumdbrecord.AssetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssetsIDs(); len(nodes) > 0 && !_u.mutation.AssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   sumdbrecord.AssetsTable,
			Columns: sumdbrecord.AssetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   sumdbrecord.AssetsTable,
			Columns: sumdbrecord.AssetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sumdbrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SumDBRecordUpdateOne is the builder for updating a single SumDBRecord entity.
type SumDBRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SumDBRecordMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SumDBRecordUpdateOne) SetUpdatedAt(v time.Time) *SumDBRecordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRecordID sets the "record_id" field.
func (_u *SumDBRecordUpdateOne) SetRecordID(v int64) *SumDBRecordUpdateOne {
	_u.mutation.ResetRecordID()
	_u.mutation.SetRecordID(v)
	return _u
}

// SetNillableRecordID sets the "record_id" field if the given value is not nil.
func (_u *SumDBRecordUpdateOne) SetNillableRecordID(v *int64) *SumDBRecordUpdateOne {
	if v != nil {
		_u.SetRecordID(*v)
	}
	return _u
}

// AddRecordID adds value to the "record_id" field.
func (_u *SumDBRecordUpdateOne) AddRecordID(v int64) *SumDBRecordUpdateOne {
	_u.mutation.AddRecordID(v)
	return _u
}

// SetPath sets the "path" field.
func (_u *SumDBRecordUpdateOne) SetPath(v string) *SumDBRecordUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *SumDBRecordUpdateOne) SetNillablePath(v *string) *SumDBRecordUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *SumDBRecordUpdateOne) SetVersion(v string) *SumDBRecordUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SumDBRecordUpdateOne) SetNillableVersion(v *string) *SumDBRecordUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetData sets the "data" field.
func (_u *SumDBRecordUpdateOne) SetData(v []byte) *SumDBRecordUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// AddAssetIDs adds the "assets" edge to the Asset entity by IDs.
func (_u *SumDBRecordUpdateOne) AddAssetIDs(ids ...int) *SumDBRecordUpdateOne {
	_u.mutation.AddAssetIDs(ids...)
	return _u
}

// AddAssets adds the "assets" edges to the Asset entity.
func (_u *SumDBRecordUpdateOne) AddAssets(v ...*Asset) *SumDBRecordUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssetIDs(ids...)
}

// Mutation returns the SumDBRecordMutation object of the builder.
func (_u *SumDBRecordUpdateOne) Mutation() *SumDBRecordMutation {
	return _u.mutation
}

// ClearAssets clears all "assets" edges to the Asset entity.
func (_u *SumDBRecordUpdateOne) ClearAssets() *SumDBRecordUpdateOne {
	_u.mutation.ClearAssets()
	return _u
}

// RemoveAssetIDs removes the "assets" edge to Asset entities by IDs.
func (_u *SumDBRecordUpdateOne) RemoveAssetIDs(ids ...int) *SumDBRecordUpdateOne {
	_u.mutation.RemoveAssetIDs(ids...)
	return _u
}

// RemoveAssets removes "assets" edges to Asset entities.
func (_u *SumDBRecordUpdateOne) RemoveAssets(v ...*Asset) *SumDBRecordUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssetIDs(ids...)
}

// Where appends a list predicates to the SumDBRecordUpdate builder.
func (_u *SumDBRecordUpdateOne) Where(ps ...predicate.SumDBRecord) *SumDBRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SumDBRecordUpdateOne) Select(field string, fields ...string) *SumDBRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SumDBRecord entity.
func (_u *SumDBRecordUpdateOne) Save(ctx context.Context) (*SumDBRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SumDBRecordUpdateOne) SaveX(ctx context.Context) *SumDBRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SumDBRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SumDBRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SumDBRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sumdbrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SumDBRecordUpdateOne) check() error {
	if v, ok := _u.mutation.Path(); ok {
		if err := sumdbrecord.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "SumDBRecord.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := sumdbrecord.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "SumDBRecord.version": %w`, err)}
		}
	}
	if _u.mutation.TreeCleared() && len(_u.mutation.TreeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SumDBRecord.tree"`)
	}
	return nil
}

func (_u *SumDBRecordUpdateOne) sqlSave(ctx context.Context) (_node *SumDBRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sumdbrecord.Table, sumdbrecord.Columns, sqlgraph.NewFieldSpec(sumdbrecord.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SumDBRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sumdbrecord.FieldID)
		for _, f := range fields {
			if !sumdbrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sumdbrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sumdbrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RecordID(); ok {
		_spec.SetField(sumdbrecord.FieldRecordID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecordID(); ok {
		_spec.AddField(sumdbrecord.FieldRecordID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(sumdbrecord.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(sumdbrecord.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(sumdbrecord.FieldData, field.TypeBytes, value)
	}
	if _u.mutation.AssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   sumdbrecord.AssetsTable,
			Columns: sumdbrecord.AssetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssetsIDs(); len(nodes) > 0 && !_u.mutation.AssetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   sumdbrecord.AssetsTable,
			Columns: sumdbrecord.AssetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   sumdbrecord.AssetsTable,
			Columns: sumdbrecord.AssetsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SumDBRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sumdbrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
