// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pseudomuto/pacman/internal/crypto"
	"github.com/pseudomuto/pacman/internal/ent/sumdbhash"
	"github.com/pseudomuto/pacman/internal/ent/sumdbrecord"
	"github.com/pseudomuto/pacman/internal/ent/sumdbtree"
)

// SumDBTreeCreate is the builder for creating a SumDBTree entity.
type SumDBTreeCreate struct {
	config
	mutation *SumDBTreeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SumDBTreeCreate) SetCreatedAt(v time.Time) *SumDBTreeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SumDBTreeCreate) SetNillableCreatedAt(v *time.Time) *SumDBTreeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SumDBTreeCreate) SetUpdatedAt(v time.Time) *SumDBTreeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SumDBTreeCreate) SetNillableUpdatedAt(v *time.Time) *SumDBTreeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *SumDBTreeCreate) SetName(v string) *SumDBTreeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSize sets the "size" field.
func (_c *SumDBTreeCreate) SetSize(v int64) *SumDBTreeCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetSignerKey sets the "signer_key" field.
func (_c *SumDBTreeCreate) SetSignerKey(v crypto.Secret) *SumDBTreeCreate {
	_c.mutation.SetSignerKey(v)
	return _c
}

// SetVerifierKey sets the "verifier_key" field.
func (_c *SumDBTreeCreate) SetVerifierKey(v string) *SumDBTreeCreate {
	_c.mutation.SetVerifierKey(v)
	return _c
}

// AddHashIDs adds the "hashes" edge to the SumDBHash entity by IDs.
func (_c *SumDBTreeCreate) AddHashIDs(ids ...int) *SumDBTreeCreate {
	_c.mutation.AddHashIDs(ids...)
	return _c
}

// AddHashes adds the "hashes" edges to the SumDBHash entity.
func (_c *SumDBTreeCreate) AddHashes(v ...*SumDBHash) *SumDBTreeCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddHashIDs(ids...)
}

// AddRecordIDs adds the "records" edge to the SumDBRecord entity by IDs.
func (_c *SumDBTreeCreate) AddRecordIDs(ids ...int) *SumDBTreeCreate {
	_c.mutation.AddRecordIDs(ids...)
	return _c
}

// AddRecords adds the "records" edges to the SumDBRecord entity.
func (_c *SumDBTreeCreate) AddRecords(v ...*SumDBRecord) *SumDBTreeCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecordIDs(ids...)
}

// Mutation returns the SumDBTreeMutation object of the builder.
func (_c *SumDBTreeCreate) Mutation() *SumDBTreeMutation {
	return _c.mutation
}

// Save creates the SumDBTree in the database.
func (_c *SumDBTreeCreate) Save(ctx context.Context) (*SumDBTree, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SumDBTreeCreate) SaveX(ctx context.Context) *SumDBTree {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SumDBTreeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SumDBTreeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SumDBTreeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sumdbtree.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sumdbtree.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SumDBTreeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SumDBTree.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SumDBTree.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SumDBTree.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := sumdbtree.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SumDBTree.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "SumDBTree.size"`)}
	}
	if _, ok := _c.mutation.SignerKey(); !ok {
		return &ValidationError{Name: "signer_key", err: errors.New(`ent: missing required field "SumDBTree.signer_key"`)}
	}
	if v, ok := _c.mutation.SignerKey(); ok {
		if err := sumdbtree.SignerKeyValidator(string(v)); err != nil {
			return &ValidationError{Name: "signer_key", err: fmt.Errorf(`ent: validator failed for field "SumDBTree.signer_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VerifierKey(); !ok {
		return &ValidationError{Name: "verifier_key", err: errors.New(`ent: missing required field "SumDBTree.verifier_key"`)}
	}
	if v, ok := _c.mutation.VerifierKey(); ok {
		if err := sumdbtree.VerifierKeyValidator(v); err != nil {
			return &ValidationError{Name: "verifier_key", err: fmt.Errorf(`ent: validator failed for field "SumDBTree.verifier_key": %w`, err)}
		}
	}
	return nil
}

func (_c *SumDBTreeCreate) sqlSave(ctx context.Context) (*SumDBTree, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SumDBTreeCreate) createSpec() (*SumDBTree, *sqlgraph.CreateSpec) {
	var (
		_node = &SumDBTree{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sumdbtree.Table, sqlgraph.NewFieldSpec(sumdbtree.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sumdbtree.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sumdbtree.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(sumdbtree.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(sumdbtree.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.SignerKey(); ok {
		_spec.SetField(sumdbtree.FieldSignerKey, field.TypeString, value)
		_node.SignerKey = value
	}
	if value, ok := _c.mutation.VerifierKey(); ok {
		_spec.SetField(sumdbtree.FieldVerifierKey, field.TypeString, value)
		_node.VerifierKey = value
	}
	if nodes := _c.mutation.HashesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sumdbtree.HashesTable,
			Columns: []string{sumdbtree.HashesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbhash.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sumdbtree.RecordsTable,
			Columns: []string{sumdbtree.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SumDBTree.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SumDBTreeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SumDBTreeCreate) OnConflict(opts ...sql.ConflictOption) *SumDBTreeUpsertOne {
	_c.conflict = opts
	return &SumDBTreeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SumDBTree.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SumDBTreeCreate) OnConflictColumns(columns ...string) *SumDBTreeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SumDBTreeUpsertOne{
		create: _c,
	}
}

type (
	// SumDBTreeUpsertOne is the builder for "upsert"-ing
	//  one SumDBTree node.
	SumDBTreeUpsertOne struct {
		create *SumDBTreeCreate
	}

	// SumDBTreeUpsert is the "OnConflict" setter.
	SumDBTreeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SumDBTreeUpsert) SetUpdatedAt(v time.Time) *SumDBTreeUpsert {
	u.Set(sumdbtree.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SumDBTreeUpsert) UpdateUpdatedAt() *SumDBTreeUpsert {
	u.SetExcluded(sumdbtree.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *SumDBTreeUpsert) SetName(v string) *SumDBTreeUpsert {
	u.Set(sumdbtree.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SumDBTreeUpsert) UpdateName() *SumDBTreeUpsert {
	u.SetExcluded(sumdbtree.FieldName)
	return u
}

// SetSize sets the "size" field.
func (u *SumDBTreeUpsert) SetSize(v int64) *SumDBTreeUpsert {
	u.Set(sumdbtree.FieldSize, v)
	return u
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *SumDBTreeUpsert) UpdateSize() *SumDBTreeUpsert {
	u.SetExcluded(sumdbtree.FieldSize)
	return u
}

// AddSize adds v to the "size" field.
func (u *SumDBTreeUpsert) AddSize(v int64) *SumDBTreeUpsert {
	u.Add(sumdbtree.FieldSize, v)
	return u
}

// SetSignerKey sets the "signer_key" field.
func (u *SumDBTreeUpsert) SetSignerKey(v crypto.Secret) *SumDBTreeUpsert {
	u.Set(sumdbtree.FieldSignerKey, v)
	return u
}

// UpdateSignerKey sets the "signer_key" field to the value that was provided on create.
func (u *SumDBTreeUpsert) UpdateSignerKey() *SumDBTreeUpsert {
	u.SetExcluded(sumdbtree.FieldSignerKey)
	return u
}

// SetVerifierKey sets the "verifier_key" field.
func (u *SumDBTreeUpsert) SetVerifierKey(v string) *SumDBTreeUpsert {
	u.Set(sumdbtree.FieldVerifierKey, v)
	return u
}

// UpdateVerifierKey sets the "verifier_key" field to the value that was provided on create.
func (u *SumDBTreeUpsert) UpdateVerifierKey() *SumDBTreeUpsert {
	u.SetExcluded(sumdbtree.FieldVerifierKey)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SumDBTree.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SumDBTreeUpsertOne) UpdateNewValues() *SumDBTreeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(sumdbtree.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SumDBTree.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SumDBTreeUpsertOne) Ignore() *SumDBTreeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SumDBTreeUpsertOne) DoNothing() *SumDBTreeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SumDBTreeCreate.OnConflict
// documentation for more info.
func (u *SumDBTreeUpsertOne) Update(set func(*SumDBTreeUpsert)) *SumDBTreeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SumDBTreeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SumDBTreeUpsertOne) SetUpdatedAt(v time.Time) *SumDBTreeUpsertOne {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SumDBTreeUpsertOne) UpdateUpdatedAt() *SumDBTreeUpsertOne {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *SumDBTreeUpsertOne) SetName(v string) *SumDBTreeUpsertOne {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SumDBTreeUpsertOne) UpdateName() *SumDBTreeUpsertOne {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.UpdateName()
	})
}

// SetSize sets the "size" field.
func (u *SumDBTreeUpsertOne) SetSize(v int64) *SumDBTreeUpsertOne {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *SumDBTreeUpsertOne) AddSize(v int64) *SumDBTreeUpsertOne {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *SumDBTreeUpsertOne) UpdateSize() *SumDBTreeUpsertOne {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.UpdateSize()
	})
}

// SetSignerKey sets the "signer_key" field.
func (u *SumDBTreeUpsertOne) SetSignerKey(v crypto.Secret) *SumDBTreeUpsertOne {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.SetSignerKey(v)
	})
}

// UpdateSignerKey sets the "signer_key" field to the value that was provided on create.
func (u *SumDBTreeUpsertOne) UpdateSignerKey() *SumDBTreeUpsertOne {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.UpdateSignerKey()
	})
}

// SetVerifierKey sets the "verifier_key" field.
func (u *SumDBTreeUpsertOne) SetVerifierKey(v string) *SumDBTreeUpsertOne {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.SetVerifierKey(v)
	})
}

// UpdateVerifierKey sets the "verifier_key" field to the value that was provided on create.
func (u *SumDBTreeUpsertOne) UpdateVerifierKey() *SumDBTreeUpsertOne {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.UpdateVerifierKey()
	})
}

// Exec executes the query.
func (u *SumDBTreeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SumDBTreeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SumDBTreeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SumDBTreeUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SumDBTreeUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SumDBTreeCreateBulk is the builder for creating many SumDBTree entities in bulk.
type SumDBTreeCreateBulk struct {
	config
	err      error
	builders []*SumDBTreeCreate
	conflict []sql.ConflictOption
}

// Save creates the SumDBTree entities in the database.
func (_c *SumDBTreeCreateBulk) Save(ctx context.Context) ([]*SumDBTree, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SumDBTree, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SumDBTreeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SumDBTreeCreateBulk) SaveX(ctx context.Context) []*SumDBTree {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SumDBTreeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SumDBTreeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SumDBTree.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SumDBTreeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SumDBTreeCreateBulk) OnConflict(opts ...sql.ConflictOption) *SumDBTreeUpsertBulk {
	_c.conflict = opts
	return &SumDBTreeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SumDBTree.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SumDBTreeCreateBulk) OnConflictColumns(columns ...string) *SumDBTreeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SumDBTreeUpsertBulk{
		create: _c,
	}
}

// SumDBTreeUpsertBulk is the builder for "upsert"-ing
// a bulk of SumDBTree nodes.
type SumDBTreeUpsertBulk struct {
	create *SumDBTreeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SumDBTree.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SumDBTreeUpsertBulk) UpdateNewValues() *SumDBTreeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(sumdbtree.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SumDBTree.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SumDBTreeUpsertBulk) Ignore() *SumDBTreeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SumDBTreeUpsertBulk) DoNothing() *SumDBTreeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SumDBTreeCreateBulk.OnConflict
// documentation for more info.
func (u *SumDBTreeUpsertBulk) Update(set func(*SumDBTreeUpsert)) *SumDBTreeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SumDBTreeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SumDBTreeUpsertBulk) SetUpdatedAt(v time.Time) *SumDBTreeUpsertBulk {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SumDBTreeUpsertBulk) UpdateUpdatedAt() *SumDBTreeUpsertBulk {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *SumDBTreeUpsertBulk) SetName(v string) *SumDBTreeUpsertBulk {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SumDBTreeUpsertBulk) UpdateName() *SumDBTreeUpsertBulk {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.UpdateName()
	})
}

// SetSize sets the "size" field.
func (u *SumDBTreeUpsertBulk) SetSize(v int64) *SumDBTreeUpsertBulk {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *SumDBTreeUpsertBulk) AddSize(v int64) *SumDBTreeUpsertBulk {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *SumDBTreeUpsertBulk) UpdateSize() *SumDBTreeUpsertBulk {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.UpdateSize()
	})
}

// SetSignerKey sets the "signer_key" field.
func (u *SumDBTreeUpsertBulk) SetSignerKey(v crypto.Secret) *SumDBTreeUpsertBulk {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.SetSignerKey(v)
	})
}

// UpdateSignerKey sets the "signer_key" field to the value that was provided on create.
func (u *SumDBTreeUpsertBulk) UpdateSignerKey() *SumDBTreeUpsertBulk {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.UpdateSignerKey()
	})
}

// SetVerifierKey sets the "verifier_key" field.
func (u *SumDBTreeUpsertBulk) SetVerifierKey(v string) *SumDBTreeUpsertBulk {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.SetVerifierKey(v)
	})
}

// UpdateVerifierKey sets the "verifier_key" field to the value that was provided on create.
func (u *SumDBTreeUpsertBulk) UpdateVerifierKey() *SumDBTreeUpsertBulk {
	return u.Update(func(s *SumDBTreeUpsert) {
		s.UpdateVerifierKey()
	})
}

// Exec executes the query.
func (u *SumDBTreeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SumDBTreeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SumDBTreeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SumDBTreeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
