// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/pseudomuto/pacman/internal/ent/sumdbrecord"
	"github.com/pseudomuto/pacman/internal/ent/sumdbtree"
)

// SumDBRecord is the model entity for the SumDBRecord schema.
type SumDBRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// When this object was initially created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The last time this object was modified
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RecordID holds the value of the "record_id" field.
	RecordID int64 `json:"record_id,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Data holds the value of the "data" field.
	Data []byte `json:"data,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SumDBRecordQuery when eager-loading is set.
	Edges        SumDBRecordEdges `json:"edges"`
	tree_id      *int
	selectValues sql.SelectValues
}

// SumDBRecordEdges holds the relations/edges for other nodes in the graph.
type SumDBRecordEdges struct {
	// Tree holds the value of the tree edge.
	Tree *SumDBTree `json:"tree,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TreeOrErr returns the Tree value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SumDBRecordEdges) TreeOrErr() (*SumDBTree, error) {
	if e.Tree != nil {
		return e.Tree, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: sumdbtree.Label}
	}
	return nil, &NotLoadedError{edge: "tree"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SumDBRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sumdbrecord.FieldData:
			values[i] = new([]byte)
		case sumdbrecord.FieldID, sumdbrecord.FieldRecordID:
			values[i] = new(sql.NullInt64)
		case sumdbrecord.FieldPath, sumdbrecord.FieldVersion:
			values[i] = new(sql.NullString)
		case sumdbrecord.FieldCreatedAt, sumdbrecord.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case sumdbrecord.ForeignKeys[0]: // tree_id
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SumDBRecord fields.
func (_m *SumDBRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sumdbrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case sumdbrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sumdbrecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sumdbrecord.FieldRecordID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field record_id", values[i])
			} else if value.Valid {
				_m.RecordID = value.Int64
			}
		case sumdbrecord.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case sumdbrecord.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case sumdbrecord.FieldData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value != nil {
				_m.Data = *value
			}
		case sumdbrecord.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field tree_id", value)
			} else if value.Valid {
				_m.tree_id = new(int)
				*_m.tree_id = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SumDBRecord.
// This includes values selected through modifiers, order, etc.
func (_m *SumDBRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTree queries the "tree" edge of the SumDBRecord entity.
func (_m *SumDBRecord) QueryTree() *SumDBTreeQuery {
	return NewSumDBRecordClient(_m.config).QueryTree(_m)
}

// Update returns a builder for updating this SumDBRecord.
// Note that you need to call SumDBRecord.Unwrap() before calling this method if this SumDBRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SumDBRecord) Update() *SumDBRecordUpdateOne {
	return NewSumDBRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SumDBRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SumDBRecord) Unwrap() *SumDBRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SumDBRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SumDBRecord) String() string {
	var builder strings.Builder
	builder.WriteString("SumDBRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("record_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecordID))
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("data=")
	builder.WriteString(fmt.Sprintf("%v", _m.Data))
	builder.WriteByte(')')
	return builder.String()
}

// SumDBRecords is a parsable slice of SumDBRecord.
type SumDBRecords []*SumDBRecord
