// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pseudomuto/pacman/internal/ent/predicate"
	"github.com/pseudomuto/pacman/internal/ent/sumdbtree"
)

// SumDBTreeDelete is the builder for deleting a SumDBTree entity.
type SumDBTreeDelete struct {
	config
	hooks    []Hook
	mutation *SumDBTreeMutation
}

// Where appends a list predicates to the SumDBTreeDelete builder.
func (_d *SumDBTreeDelete) Where(ps ...predicate.SumDBTree) *SumDBTreeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SumDBTreeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SumDBTreeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SumDBTreeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sumdbtree.Table, sqlgraph.NewFieldSpec(sumdbtree.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SumDBTreeDeleteOne is the builder for deleting a single SumDBTree entity.
type SumDBTreeDeleteOne struct {
	_d *SumDBTreeDelete
}

// Where appends a list predicates to the SumDBTreeDelete builder.
func (_d *SumDBTreeDeleteOne) Where(ps ...predicate.SumDBTree) *SumDBTreeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SumDBTreeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sumdbtree.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SumDBTreeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
