// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/pseudomuto/pacman/internal/crypto"
	"github.com/pseudomuto/pacman/internal/ent/sumdbtree"
)

// SumDBTree is the model entity for the SumDBTree schema.
type SumDBTree struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// When this object was initially created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The last time this object was modified
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Size holds the value of the "size" field.
	Size int64 `json:"size,omitempty"`
	// SignerKey holds the value of the "signer_key" field.
	SignerKey crypto.Secret `json:"signer_key,omitempty"`
	// VerifierKey holds the value of the "verifier_key" field.
	VerifierKey string `json:"verifier_key,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SumDBTreeQuery when eager-loading is set.
	Edges        SumDBTreeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SumDBTreeEdges holds the relations/edges for other nodes in the graph.
type SumDBTreeEdges struct {
	// Hashes holds the value of the hashes edge.
	Hashes []*SumDBHash `json:"hashes,omitempty"`
	// Records holds the value of the records edge.
	Records []*SumDBRecord `json:"records,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// HashesOrErr returns the Hashes value or an error if the edge
// was not loaded in eager-loading.
func (e SumDBTreeEdges) HashesOrErr() ([]*SumDBHash, error) {
	if e.loadedTypes[0] {
		return e.Hashes, nil
	}
	return nil, &NotLoadedError{edge: "hashes"}
}

// RecordsOrErr returns the Records value or an error if the edge
// was not loaded in eager-loading.
func (e SumDBTreeEdges) RecordsOrErr() ([]*SumDBRecord, error) {
	if e.loadedTypes[1] {
		return e.Records, nil
	}
	return nil, &NotLoadedError{edge: "records"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SumDBTree) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sumdbtree.FieldSignerKey:
			values[i] = new(crypto.Secret)
		case sumdbtree.FieldID, sumdbtree.FieldSize:
			values[i] = new(sql.NullInt64)
		case sumdbtree.FieldName, sumdbtree.FieldVerifierKey:
			values[i] = new(sql.NullString)
		case sumdbtree.FieldCreatedAt, sumdbtree.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SumDBTree fields.
func (_m *SumDBTree) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sumdbtree.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case sumdbtree.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sumdbtree.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sumdbtree.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case sumdbtree.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = value.Int64
			}
		case sumdbtree.FieldSignerKey:
			if value, ok := values[i].(*crypto.Secret); !ok {
				return fmt.Errorf("unexpected type %T for field signer_key", values[i])
			} else if value != nil {
				_m.SignerKey = *value
			}
		case sumdbtree.FieldVerifierKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field verifier_key", values[i])
			} else if value.Valid {
				_m.VerifierKey = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SumDBTree.
// This includes values selected through modifiers, order, etc.
func (_m *SumDBTree) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHashes queries the "hashes" edge of the SumDBTree entity.
func (_m *SumDBTree) QueryHashes() *SumDBHashQuery {
	return NewSumDBTreeClient(_m.config).QueryHashes(_m)
}

// QueryRecords queries the "records" edge of the SumDBTree entity.
func (_m *SumDBTree) QueryRecords() *SumDBRecordQuery {
	return NewSumDBTreeClient(_m.config).QueryRecords(_m)
}

// Update returns a builder for updating this SumDBTree.
// Note that you need to call SumDBTree.Unwrap() before calling this method if this SumDBTree
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SumDBTree) Update() *SumDBTreeUpdateOne {
	return NewSumDBTreeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SumDBTree entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SumDBTree) Unwrap() *SumDBTree {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SumDBTree is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SumDBTree) String() string {
	var builder strings.Builder
	builder.WriteString("SumDBTree(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", _m.Size))
	builder.WriteString(", ")
	builder.WriteString("signer_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.SignerKey))
	builder.WriteString(", ")
	builder.WriteString("verifier_key=")
	builder.WriteString(_m.VerifierKey)
	builder.WriteByte(')')
	return builder.String()
}

// SumDBTrees is a parsable slice of SumDBTree.
type SumDBTrees []*SumDBTree
