// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pseudomuto/pacman/internal/ent/predicate"
	"github.com/pseudomuto/pacman/internal/ent/sumdbhash"
)

// SumDBHashUpdate is the builder for updating SumDBHash entities.
type SumDBHashUpdate struct {
	config
	hooks    []Hook
	mutation *SumDBHashMutation
}

// Where appends a list predicates to the SumDBHashUpdate builder.
func (_u *SumDBHashUpdate) Where(ps ...predicate.SumDBHash) *SumDBHashUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SumDBHashUpdate) SetUpdatedAt(v time.Time) *SumDBHashUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIndex sets the "index" field.
func (_u *SumDBHashUpdate) SetIndex(v int64) *SumDBHashUpdate {
	_u.mutation.ResetIndex()
	_u.mutation.SetIndex(v)
	return _u
}

// SetNillableIndex sets the "index" field if the given value is not nil.
func (_u *SumDBHashUpdate) SetNillableIndex(v *int64) *SumDBHashUpdate {
	if v != nil {
		_u.SetIndex(*v)
	}
	return _u
}

// AddIndex adds value to the "index" field.
func (_u *SumDBHashUpdate) AddIndex(v int64) *SumDBHashUpdate {
	_u.mutation.AddIndex(v)
	return _u
}

// SetHash sets the "hash" field.
func (_u *SumDBHashUpdate) SetHash(v []byte) *SumDBHashUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// Mutation returns the SumDBHashMutation object of the builder.
func (_u *SumDBHashUpdate) Mutation() *SumDBHashMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SumDBHashUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SumDBHashUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SumDBHashUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SumDBHashUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SumDBHashUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sumdbhash.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SumDBHashUpdate) check() error {
	if _u.mutation.TreeCleared() && len(_u.mutation.TreeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SumDBHash.tree"`)
	}
	return nil
}

func (_u *SumDBHashUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sumdbhash.Table, sumdbhash.Columns, sqlgraph.NewFieldSpec(sumdbhash.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sumdbhash.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Index(); ok {
		_spec.SetField(sumdbhash.FieldIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedIndex(); ok {
		_spec.AddField(sumdbhash.FieldIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(sumdbhash.FieldHash, field.TypeBytes, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sumdbhash.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SumDBHashUpdateOne is the builder for updating a single SumDBHash entity.
type SumDBHashUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SumDBHashMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SumDBHashUpdateOne) SetUpdatedAt(v time.Time) *SumDBHashUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIndex sets the "index" field.
func (_u *SumDBHashUpdateOne) SetIndex(v int64) *SumDBHashUpdateOne {
	_u.mutation.ResetIndex()
	_u.mutation.SetIndex(v)
	return _u
}

// SetNillableIndex sets the "index" field if the given value is not nil.
func (_u *SumDBHashUpdateOne) SetNillableIndex(v *int64) *SumDBHashUpdateOne {
	if v != nil {
		_u.SetIndex(*v)
	}
	return _u
}

// AddIndex adds value to the "index" field.
func (_u *SumDBHashUpdateOne) AddIndex(v int64) *SumDBHashUpdateOne {
	_u.mutation.AddIndex(v)
	return _u
}

// SetHash sets the "hash" field.
func (_u *SumDBHashUpdateOne) SetHash(v []byte) *SumDBHashUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// Mutation returns the SumDBHashMutation object of the builder.
func (_u *SumDBHashUpdateOne) Mutation() *SumDBHashMutation {
	return _u.mutation
}

// Where appends a list predicates to the SumDBHashUpdate builder.
func (_u *SumDBHashUpdateOne) Where(ps ...predicate.SumDBHash) *SumDBHashUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SumDBHashUpdateOne) Select(field string, fields ...string) *SumDBHashUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SumDBHash entity.
func (_u *SumDBHashUpdateOne) Save(ctx context.Context) (*SumDBHash, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SumDBHashUpdateOne) SaveX(ctx context.Context) *SumDBHash {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SumDBHashUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SumDBHashUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SumDBHashUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sumdbhash.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SumDBHashUpdateOne) check() error {
	if _u.mutation.TreeCleared() && len(_u.mutation.TreeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SumDBHash.tree"`)
	}
	return nil
}

func (_u *SumDBHashUpdateOne) sqlSave(ctx context.Context) (_node *SumDBHash, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sumdbhash.Table, sumdbhash.Columns, sqlgraph.NewFieldSpec(sumdbhash.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SumDBHash.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sumdbhash.FieldID)
		for _, f := range fields {
			if !sumdbhash.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sumdbhash.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sumdbhash.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Index(); ok {
		_spec.SetField(sumdbhash.FieldIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedIndex(); ok {
		_spec.AddField(sumdbhash.FieldIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(sumdbhash.FieldHash, field.TypeBytes, value)
	}
	_node = &SumDBHash{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sumdbhash.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
