// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pseudomuto/pacman/internal/ent/sumdbrecord"
	"github.com/pseudomuto/pacman/internal/ent/sumdbtree"
)

// SumDBRecordCreate is the builder for creating a SumDBRecord entity.
type SumDBRecordCreate struct {
	config
	mutation *SumDBRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SumDBRecordCreate) SetCreatedAt(v time.Time) *SumDBRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SumDBRecordCreate) SetNillableCreatedAt(v *time.Time) *SumDBRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SumDBRecordCreate) SetUpdatedAt(v time.Time) *SumDBRecordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SumDBRecordCreate) SetNillableUpdatedAt(v *time.Time) *SumDBRecordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRecordID sets the "record_id" field.
func (_c *SumDBRecordCreate) SetRecordID(v int64) *SumDBRecordCreate {
	_c.mutation.SetRecordID(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *SumDBRecordCreate) SetPath(v string) *SumDBRecordCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *SumDBRecordCreate) SetVersion(v string) *SumDBRecordCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetData sets the "data" field.
func (_c *SumDBRecordCreate) SetData(v []byte) *SumDBRecordCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetTreeID sets the "tree" edge to the SumDBTree entity by ID.
func (_c *SumDBRecordCreate) SetTreeID(id int) *SumDBRecordCreate {
	_c.mutation.SetTreeID(id)
	return _c
}

// SetTree sets the "tree" edge to the SumDBTree entity.
func (_c *SumDBRecordCreate) SetTree(v *SumDBTree) *SumDBRecordCreate {
	return _c.SetTreeID(v.ID)
}

// Mutation returns the SumDBRecordMutation object of the builder.
func (_c *SumDBRecordCreate) Mutation() *SumDBRecordMutation {
	return _c.mutation
}

// Save creates the SumDBRecord in the database.
func (_c *SumDBRecordCreate) Save(ctx context.Context) (*SumDBRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SumDBRecordCreate) SaveX(ctx context.Context) *SumDBRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SumDBRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SumDBRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SumDBRecordCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sumdbrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sumdbrecord.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SumDBRecordCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SumDBRecord.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SumDBRecord.updated_at"`)}
	}
	if _, ok := _c.mutation.RecordID(); !ok {
		return &ValidationError{Name: "record_id", err: errors.New(`ent: missing required field "SumDBRecord.record_id"`)}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "SumDBRecord.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := sumdbrecord.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "SumDBRecord.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "SumDBRecord.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := sumdbrecord.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "SumDBRecord.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "SumDBRecord.data"`)}
	}
	if len(_c.mutation.TreeIDs()) == 0 {
		return &ValidationError{Name: "tree", err: errors.New(`ent: missing required edge "SumDBRecord.tree"`)}
	}
	return nil
}

func (_c *SumDBRecordCreate) sqlSave(ctx context.Context) (*SumDBRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SumDBRecordCreate) createSpec() (*SumDBRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &SumDBRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sumdbrecord.Table, sqlgraph.NewFieldSpec(sumdbrecord.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sumdbrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sumdbrecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.RecordID(); ok {
		_spec.SetField(sumdbrecord.FieldRecordID, field.TypeInt64, value)
		_node.RecordID = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(sumdbrecord.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(sumdbrecord.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(sumdbrecord.FieldData, field.TypeBytes, value)
		_node.Data = value
	}
	if nodes := _c.mutation.TreeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sumdbrecord.TreeTable,
			Columns: []string{sumdbrecord.TreeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sumdbtree.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tree_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SumDBRecord.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SumDBRecordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SumDBRecordCreate) OnConflict(opts ...sql.ConflictOption) *SumDBRecordUpsertOne {
	_c.conflict = opts
	return &SumDBRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SumDBRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SumDBRecordCreate) OnConflictColumns(columns ...string) *SumDBRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SumDBRecordUpsertOne{
		create: _c,
	}
}

type (
	// SumDBRecordUpsertOne is the builder for "upsert"-ing
	//  one SumDBRecord node.
	SumDBRecordUpsertOne struct {
		create *SumDBRecordCreate
	}

	// SumDBRecordUpsert is the "OnConflict" setter.
	SumDBRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SumDBRecordUpsert) SetUpdatedAt(v time.Time) *SumDBRecordUpsert {
	u.Set(sumdbrecord.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SumDBRecordUpsert) UpdateUpdatedAt() *SumDBRecordUpsert {
	u.SetExcluded(sumdbrecord.FieldUpdatedAt)
	return u
}

// SetRecordID sets the "record_id" field.
func (u *SumDBRecordUpsert) SetRecordID(v int64) *SumDBRecordUpsert {
	u.Set(sumdbrecord.FieldRecordID, v)
	return u
}

// UpdateRecordID sets the "record_id" field to the value that was provided on create.
func (u *SumDBRecordUpsert) UpdateRecordID() *SumDBRecordUpsert {
	u.SetExcluded(sumdbrecord.FieldRecordID)
	return u
}

// AddRecordID adds v to the "record_id" field.
func (u *SumDBRecordUpsert) AddRecordID(v int64) *SumDBRecordUpsert {
	u.Add(sumdbrecord.FieldRecordID, v)
	return u
}

// SetPath sets the "path" field.
func (u *SumDBRecordUpsert) SetPath(v string) *SumDBRecordUpsert {
	u.Set(sumdbrecord.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *SumDBRecordUpsert) UpdatePath() *SumDBRecordUpsert {
	u.SetExcluded(sumdbrecord.FieldPath)
	return u
}

// SetVersion sets the "version" field.
func (u *SumDBRecordUpsert) SetVersion(v string) *SumDBRecordUpsert {
	u.Set(sumdbrecord.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SumDBRecordUpsert) UpdateVersion() *SumDBRecordUpsert {
	u.SetExcluded(sumdbrecord.FieldVersion)
	return u
}

// SetData sets the "data" field.
func (u *SumDBRecordUpsert) SetData(v []byte) *SumDBRecordUpsert {
	u.Set(sumdbrecord.FieldData, v)
	return u
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *SumDBRecordUpsert) UpdateData() *SumDBRecordUpsert {
	u.SetExcluded(sumdbrecord.FieldData)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SumDBRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SumDBRecordUpsertOne) UpdateNewValues() *SumDBRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(sumdbrecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SumDBRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SumDBRecordUpsertOne) Ignore() *SumDBRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SumDBRecordUpsertOne) DoNothing() *SumDBRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SumDBRecordCreate.OnConflict
// documentation for more info.
func (u *SumDBRecordUpsertOne) Update(set func(*SumDBRecordUpsert)) *SumDBRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SumDBRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SumDBRecordUpsertOne) SetUpdatedAt(v time.Time) *SumDBRecordUpsertOne {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SumDBRecordUpsertOne) UpdateUpdatedAt() *SumDBRecordUpsertOne {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRecordID sets the "record_id" field.
func (u *SumDBRecordUpsertOne) SetRecordID(v int64) *SumDBRecordUpsertOne {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.SetRecordID(v)
	})
}

// AddRecordID adds v to the "record_id" field.
func (u *SumDBRecordUpsertOne) AddRecordID(v int64) *SumDBRecordUpsertOne {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.AddRecordID(v)
	})
}

// UpdateRecordID sets the "record_id" field to the value that was provided on create.
func (u *SumDBRecordUpsertOne) UpdateRecordID() *SumDBRecordUpsertOne {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.UpdateRecordID()
	})
}

// SetPath sets the "path" field.
func (u *SumDBRecordUpsertOne) SetPath(v string) *SumDBRecordUpsertOne {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *SumDBRecordUpsertOne) UpdatePath() *SumDBRecordUpsertOne {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.UpdatePath()
	})
}

// SetVersion sets the "version" field.
func (u *SumDBRecordUpsertOne) SetVersion(v string) *SumDBRecordUpsertOne {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SumDBRecordUpsertOne) UpdateVersion() *SumDBRecordUpsertOne {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.UpdateVersion()
	})
}

// SetData sets the "data" field.
func (u *SumDBRecordUpsertOne) SetData(v []byte) *SumDBRecordUpsertOne {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *SumDBRecordUpsertOne) UpdateData() *SumDBRecordUpsertOne {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.UpdateData()
	})
}

// Exec executes the query.
func (u *SumDBRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SumDBRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SumDBRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SumDBRecordUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SumDBRecordUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SumDBRecordCreateBulk is the builder for creating many SumDBRecord entities in bulk.
type SumDBRecordCreateBulk struct {
	config
	err      error
	builders []*SumDBRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the SumDBRecord entities in the database.
func (_c *SumDBRecordCreateBulk) Save(ctx context.Context) ([]*SumDBRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SumDBRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SumDBRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SumDBRecordCreateBulk) SaveX(ctx context.Context) []*SumDBRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SumDBRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SumDBRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SumDBRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SumDBRecordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SumDBRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *SumDBRecordUpsertBulk {
	_c.conflict = opts
	return &SumDBRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SumDBRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SumDBRecordCreateBulk) OnConflictColumns(columns ...string) *SumDBRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SumDBRecordUpsertBulk{
		create: _c,
	}
}

// SumDBRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of SumDBRecord nodes.
type SumDBRecordUpsertBulk struct {
	create *SumDBRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SumDBRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SumDBRecordUpsertBulk) UpdateNewValues() *SumDBRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(sumdbrecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SumDBRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SumDBRecordUpsertBulk) Ignore() *SumDBRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SumDBRecordUpsertBulk) DoNothing() *SumDBRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SumDBRecordCreateBulk.OnConflict
// documentation for more info.
func (u *SumDBRecordUpsertBulk) Update(set func(*SumDBRecordUpsert)) *SumDBRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SumDBRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SumDBRecordUpsertBulk) SetUpdatedAt(v time.Time) *SumDBRecordUpsertBulk {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SumDBRecordUpsertBulk) UpdateUpdatedAt() *SumDBRecordUpsertBulk {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRecordID sets the "record_id" field.
func (u *SumDBRecordUpsertBulk) SetRecordID(v int64) *SumDBRecordUpsertBulk {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.SetRecordID(v)
	})
}

// AddRecordID adds v to the "record_id" field.
func (u *SumDBRecordUpsertBulk) AddRecordID(v int64) *SumDBRecordUpsertBulk {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.AddRecordID(v)
	})
}

// UpdateRecordID sets the "record_id" field to the value that was provided on create.
func (u *SumDBRecordUpsertBulk) UpdateRecordID() *SumDBRecordUpsertBulk {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.UpdateRecordID()
	})
}

// SetPath sets the "path" field.
func (u *SumDBRecordUpsertBulk) SetPath(v string) *SumDBRecordUpsertBulk {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *SumDBRecordUpsertBulk) UpdatePath() *SumDBRecordUpsertBulk {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.UpdatePath()
	})
}

// SetVersion sets the "version" field.
func (u *SumDBRecordUpsertBulk) SetVersion(v string) *SumDBRecordUpsertBulk {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SumDBRecordUpsertBulk) UpdateVersion() *SumDBRecordUpsertBulk {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.UpdateVersion()
	})
}

// SetData sets the "data" field.
func (u *SumDBRecordUpsertBulk) SetData(v []byte) *SumDBRecordUpsertBulk {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *SumDBRecordUpsertBulk) UpdateData() *SumDBRecordUpsertBulk {
	return u.Update(func(s *SumDBRecordUpsert) {
		s.UpdateData()
	})
}

// Exec executes the query.
func (u *SumDBRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SumDBRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SumDBRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SumDBRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
