// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Artifact is the predicate function for artifact builders.
type Artifact func(*sql.Selector)

// ArtifactVersion is the predicate function for artifactversion builders.
type ArtifactVersion func(*sql.Selector)
