// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Archive is the predicate function for archive builders.
type Archive func(*sql.Selector)

// Artifact is the predicate function for artifact builders.
type Artifact func(*sql.Selector)

// ArtifactVersion is the predicate function for artifactversion builders.
type ArtifactVersion func(*sql.Selector)

// Asset is the predicate function for asset builders.
type Asset func(*sql.Selector)

// SumDBHash is the predicate function for sumdbhash builders.
type SumDBHash func(*sql.Selector)

// SumDBRecord is the predicate function for sumdbrecord builders.
type SumDBRecord func(*sql.Selector)

// SumDBTree is the predicate function for sumdbtree builders.
type SumDBTree func(*sql.Selector)
