// Code generated by ent, DO NOT EDIT.

package sumdbhash

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/pseudomuto/pacman/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldEQ(FieldUpdatedAt, v))
}

// Index applies equality check predicate on the "index" field. It's identical to IndexEQ.
func Index(v int64) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldEQ(FieldIndex, v))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v []byte) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldEQ(FieldHash, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldLTE(FieldUpdatedAt, v))
}

// IndexEQ applies the EQ predicate on the "index" field.
func IndexEQ(v int64) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldEQ(FieldIndex, v))
}

// IndexNEQ applies the NEQ predicate on the "index" field.
func IndexNEQ(v int64) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldNEQ(FieldIndex, v))
}

// IndexIn applies the In predicate on the "index" field.
func IndexIn(vs ...int64) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldIn(FieldIndex, vs...))
}

// IndexNotIn applies the NotIn predicate on the "index" field.
func IndexNotIn(vs ...int64) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldNotIn(FieldIndex, vs...))
}

// IndexGT applies the GT predicate on the "index" field.
func IndexGT(v int64) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldGT(FieldIndex, v))
}

// IndexGTE applies the GTE predicate on the "index" field.
func IndexGTE(v int64) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldGTE(FieldIndex, v))
}

// IndexLT applies the LT predicate on the "index" field.
func IndexLT(v int64) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldLT(FieldIndex, v))
}

// IndexLTE applies the LTE predicate on the "index" field.
func IndexLTE(v int64) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldLTE(FieldIndex, v))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v []byte) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v []byte) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...[]byte) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...[]byte) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v []byte) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v []byte) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v []byte) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v []byte) predicate.SumDBHash {
	return predicate.SumDBHash(sql.FieldLTE(FieldHash, v))
}

// HasTree applies the HasEdge predicate on the "tree" edge.
func HasTree() predicate.SumDBHash {
	return predicate.SumDBHash(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TreeTable, TreeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTreeWith applies the HasEdge predicate on the "tree" edge with a given conditions (other predicates).
func HasTreeWith(preds ...predicate.SumDBTree) predicate.SumDBHash {
	return predicate.SumDBHash(func(s *sql.Selector) {
		step := newTreeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SumDBHash) predicate.SumDBHash {
	return predicate.SumDBHash(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SumDBHash) predicate.SumDBHash {
	return predicate.SumDBHash(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SumDBHash) predicate.SumDBHash {
	return predicate.SumDBHash(sql.NotPredicates(p))
}
