// Code generated by ent, DO NOT EDIT.

package sumdbtree

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the sumdbtree type in the database.
	Label = "sum_db_tree"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSignerKey holds the string denoting the signer_key field in the database.
	FieldSignerKey = "signer_key"
	// FieldVerifierKey holds the string denoting the verifier_key field in the database.
	FieldVerifierKey = "verifier_key"
	// EdgeHashes holds the string denoting the hashes edge name in mutations.
	EdgeHashes = "hashes"
	// EdgeRecords holds the string denoting the records edge name in mutations.
	EdgeRecords = "records"
	// Table holds the table name of the sumdbtree in the database.
	Table = "sum_db_trees"
	// HashesTable is the table that holds the hashes relation/edge.
	HashesTable = "sum_db_hashes"
	// HashesInverseTable is the table name for the SumDBHash entity.
	// It exists in this package in order to avoid circular dependency with the "sumdbhash" package.
	HashesInverseTable = "sum_db_hashes"
	// HashesColumn is the table column denoting the hashes relation/edge.
	HashesColumn = "tree_id"
	// RecordsTable is the table that holds the records relation/edge.
	RecordsTable = "sum_db_records"
	// RecordsInverseTable is the table name for the SumDBRecord entity.
	// It exists in this package in order to avoid circular dependency with the "sumdbrecord" package.
	RecordsInverseTable = "sum_db_records"
	// RecordsColumn is the table column denoting the records relation/edge.
	RecordsColumn = "tree_id"
)

// Columns holds all SQL columns for sumdbtree fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldSignerKey,
	FieldVerifierKey,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SignerKeyValidator is a validator for the "signer_key" field. It is called by the builders before save.
	SignerKeyValidator func(string) error
	// VerifierKeyValidator is a validator for the "verifier_key" field. It is called by the builders before save.
	VerifierKeyValidator func(string) error
)

// OrderOption defines the ordering options for the SumDBTree queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySignerKey orders the results by the signer_key field.
func BySignerKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSignerKey, opts...).ToFunc()
}

// ByVerifierKey orders the results by the verifier_key field.
func ByVerifierKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerifierKey, opts...).ToFunc()
}

// ByHashesCount orders the results by hashes count.
func ByHashesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newHashesStep(), opts...)
	}
}

// ByHashes orders the results by hashes terms.
func ByHashes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHashesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRecordsCount orders the results by records count.
func ByRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRecordsStep(), opts...)
	}
}

// ByRecords orders the results by records terms.
func ByRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newHashesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HashesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, HashesTable, HashesColumn),
	)
}
func newRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RecordsTable, RecordsColumn),
	)
}
