// Code generated by ent, DO NOT EDIT.

package sumdbtree

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/pseudomuto/pacman/internal/crypto"
	"github.com/pseudomuto/pacman/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldEQ(FieldName, v))
}

// SignerKey applies equality check predicate on the "signer_key" field. It's identical to SignerKeyEQ.
func SignerKey(v crypto.Secret) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldEQ(FieldSignerKey, v))
}

// VerifierKey applies equality check predicate on the "verifier_key" field. It's identical to VerifierKeyEQ.
func VerifierKey(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldEQ(FieldVerifierKey, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldContainsFold(FieldName, v))
}

// SignerKeyEQ applies the EQ predicate on the "signer_key" field.
func SignerKeyEQ(v crypto.Secret) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldEQ(FieldSignerKey, v))
}

// SignerKeyNEQ applies the NEQ predicate on the "signer_key" field.
func SignerKeyNEQ(v crypto.Secret) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldNEQ(FieldSignerKey, v))
}

// SignerKeyIn applies the In predicate on the "signer_key" field.
func SignerKeyIn(vs ...crypto.Secret) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldIn(FieldSignerKey, vs...))
}

// SignerKeyNotIn applies the NotIn predicate on the "signer_key" field.
func SignerKeyNotIn(vs ...crypto.Secret) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldNotIn(FieldSignerKey, vs...))
}

// SignerKeyGT applies the GT predicate on the "signer_key" field.
func SignerKeyGT(v crypto.Secret) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldGT(FieldSignerKey, v))
}

// SignerKeyGTE applies the GTE predicate on the "signer_key" field.
func SignerKeyGTE(v crypto.Secret) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldGTE(FieldSignerKey, v))
}

// SignerKeyLT applies the LT predicate on the "signer_key" field.
func SignerKeyLT(v crypto.Secret) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldLT(FieldSignerKey, v))
}

// SignerKeyLTE applies the LTE predicate on the "signer_key" field.
func SignerKeyLTE(v crypto.Secret) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldLTE(FieldSignerKey, v))
}

// SignerKeyContains applies the Contains predicate on the "signer_key" field.
func SignerKeyContains(v crypto.Secret) predicate.SumDBTree {
	vc := string(v)
	return predicate.SumDBTree(sql.FieldContains(FieldSignerKey, vc))
}

// SignerKeyHasPrefix applies the HasPrefix predicate on the "signer_key" field.
func SignerKeyHasPrefix(v crypto.Secret) predicate.SumDBTree {
	vc := string(v)
	return predicate.SumDBTree(sql.FieldHasPrefix(FieldSignerKey, vc))
}

// SignerKeyHasSuffix applies the HasSuffix predicate on the "signer_key" field.
func SignerKeyHasSuffix(v crypto.Secret) predicate.SumDBTree {
	vc := string(v)
	return predicate.SumDBTree(sql.FieldHasSuffix(FieldSignerKey, vc))
}

// SignerKeyEqualFold applies the EqualFold predicate on the "signer_key" field.
func SignerKeyEqualFold(v crypto.Secret) predicate.SumDBTree {
	vc := string(v)
	return predicate.SumDBTree(sql.FieldEqualFold(FieldSignerKey, vc))
}

// SignerKeyContainsFold applies the ContainsFold predicate on the "signer_key" field.
func SignerKeyContainsFold(v crypto.Secret) predicate.SumDBTree {
	vc := string(v)
	return predicate.SumDBTree(sql.FieldContainsFold(FieldSignerKey, vc))
}

// VerifierKeyEQ applies the EQ predicate on the "verifier_key" field.
func VerifierKeyEQ(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldEQ(FieldVerifierKey, v))
}

// VerifierKeyNEQ applies the NEQ predicate on the "verifier_key" field.
func VerifierKeyNEQ(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldNEQ(FieldVerifierKey, v))
}

// VerifierKeyIn applies the In predicate on the "verifier_key" field.
func VerifierKeyIn(vs ...string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldIn(FieldVerifierKey, vs...))
}

// VerifierKeyNotIn applies the NotIn predicate on the "verifier_key" field.
func VerifierKeyNotIn(vs ...string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldNotIn(FieldVerifierKey, vs...))
}

// VerifierKeyGT applies the GT predicate on the "verifier_key" field.
func VerifierKeyGT(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldGT(FieldVerifierKey, v))
}

// VerifierKeyGTE applies the GTE predicate on the "verifier_key" field.
func VerifierKeyGTE(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldGTE(FieldVerifierKey, v))
}

// VerifierKeyLT applies the LT predicate on the "verifier_key" field.
func VerifierKeyLT(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldLT(FieldVerifierKey, v))
}

// VerifierKeyLTE applies the LTE predicate on the "verifier_key" field.
func VerifierKeyLTE(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldLTE(FieldVerifierKey, v))
}

// VerifierKeyContains applies the Contains predicate on the "verifier_key" field.
func VerifierKeyContains(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldContains(FieldVerifierKey, v))
}

// VerifierKeyHasPrefix applies the HasPrefix predicate on the "verifier_key" field.
func VerifierKeyHasPrefix(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldHasPrefix(FieldVerifierKey, v))
}

// VerifierKeyHasSuffix applies the HasSuffix predicate on the "verifier_key" field.
func VerifierKeyHasSuffix(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldHasSuffix(FieldVerifierKey, v))
}

// VerifierKeyEqualFold applies the EqualFold predicate on the "verifier_key" field.
func VerifierKeyEqualFold(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldEqualFold(FieldVerifierKey, v))
}

// VerifierKeyContainsFold applies the ContainsFold predicate on the "verifier_key" field.
func VerifierKeyContainsFold(v string) predicate.SumDBTree {
	return predicate.SumDBTree(sql.FieldContainsFold(FieldVerifierKey, v))
}

// HasHashes applies the HasEdge predicate on the "hashes" edge.
func HasHashes() predicate.SumDBTree {
	return predicate.SumDBTree(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, HashesTable, HashesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHashesWith applies the HasEdge predicate on the "hashes" edge with a given conditions (other predicates).
func HasHashesWith(preds ...predicate.SumDBHash) predicate.SumDBTree {
	return predicate.SumDBTree(func(s *sql.Selector) {
		step := newHashesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRecords applies the HasEdge predicate on the "records" edge.
func HasRecords() predicate.SumDBTree {
	return predicate.SumDBTree(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RecordsTable, RecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecordsWith applies the HasEdge predicate on the "records" edge with a given conditions (other predicates).
func HasRecordsWith(preds ...predicate.SumDBRecord) predicate.SumDBTree {
	return predicate.SumDBTree(func(s *sql.Selector) {
		step := newRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SumDBTree) predicate.SumDBTree {
	return predicate.SumDBTree(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SumDBTree) predicate.SumDBTree {
	return predicate.SumDBTree(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SumDBTree) predicate.SumDBTree {
	return predicate.SumDBTree(sql.NotPredicates(p))
}
