// Code generated by ent, DO NOT EDIT.

package archive

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/pseudomuto/pacman/internal/types"
)

const (
	// Label holds the string label denoting the archive type in the database.
	Label = "archive"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldCoordinate holds the string denoting the coordinate field in the database.
	FieldCoordinate = "coordinate"
	// FieldAssets holds the string denoting the assets field in the database.
	FieldAssets = "assets"
	// Table holds the table name of the archive in the database.
	Table = "archives"
)

// Columns holds all SQL columns for archive fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldType,
	FieldCoordinate,
	FieldAssets,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CoordinateValidator is a validator for the "coordinate" field. It is called by the builders before save.
	CoordinateValidator func(string) error
)

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type types.ArchiveType) error {
	switch _type.String() {
	case "gomod":
		return nil
	default:
		return fmt.Errorf("archive: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Archive queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByCoordinate orders the results by the coordinate field.
func ByCoordinate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoordinate, opts...).ToFunc()
}
