// Code generated by ent, DO NOT EDIT.

package archive

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/pseudomuto/pacman/internal/ent/predicate"
	"github.com/pseudomuto/pacman/internal/types"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Archive {
	return predicate.Archive(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Archive {
	return predicate.Archive(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Archive {
	return predicate.Archive(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Archive {
	return predicate.Archive(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Archive {
	return predicate.Archive(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Archive {
	return predicate.Archive(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Archive {
	return predicate.Archive(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldUpdatedAt, v))
}

// Coordinate applies equality check predicate on the "coordinate" field. It's identical to CoordinateEQ.
func Coordinate(v string) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldCoordinate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Archive {
	return predicate.Archive(sql.FieldLTE(FieldUpdatedAt, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v types.ArchiveType) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v types.ArchiveType) predicate.Archive {
	return predicate.Archive(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...types.ArchiveType) predicate.Archive {
	return predicate.Archive(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...types.ArchiveType) predicate.Archive {
	return predicate.Archive(sql.FieldNotIn(FieldType, vs...))
}

// CoordinateEQ applies the EQ predicate on the "coordinate" field.
func CoordinateEQ(v string) predicate.Archive {
	return predicate.Archive(sql.FieldEQ(FieldCoordinate, v))
}

// CoordinateNEQ applies the NEQ predicate on the "coordinate" field.
func CoordinateNEQ(v string) predicate.Archive {
	return predicate.Archive(sql.FieldNEQ(FieldCoordinate, v))
}

// CoordinateIn applies the In predicate on the "coordinate" field.
func CoordinateIn(vs ...string) predicate.Archive {
	return predicate.Archive(sql.FieldIn(FieldCoordinate, vs...))
}

// CoordinateNotIn applies the NotIn predicate on the "coordinate" field.
func CoordinateNotIn(vs ...string) predicate.Archive {
	return predicate.Archive(sql.FieldNotIn(FieldCoordinate, vs...))
}

// CoordinateGT applies the GT predicate on the "coordinate" field.
func CoordinateGT(v string) predicate.Archive {
	return predicate.Archive(sql.FieldGT(FieldCoordinate, v))
}

// CoordinateGTE applies the GTE predicate on the "coordinate" field.
func CoordinateGTE(v string) predicate.Archive {
	return predicate.Archive(sql.FieldGTE(FieldCoordinate, v))
}

// CoordinateLT applies the LT predicate on the "coordinate" field.
func CoordinateLT(v string) predicate.Archive {
	return predicate.Archive(sql.FieldLT(FieldCoordinate, v))
}

// CoordinateLTE applies the LTE predicate on the "coordinate" field.
func CoordinateLTE(v string) predicate.Archive {
	return predicate.Archive(sql.FieldLTE(FieldCoordinate, v))
}

// CoordinateContains applies the Contains predicate on the "coordinate" field.
func CoordinateContains(v string) predicate.Archive {
	return predicate.Archive(sql.FieldContains(FieldCoordinate, v))
}

// CoordinateHasPrefix applies the HasPrefix predicate on the "coordinate" field.
func CoordinateHasPrefix(v string) predicate.Archive {
	return predicate.Archive(sql.FieldHasPrefix(FieldCoordinate, v))
}

// CoordinateHasSuffix applies the HasSuffix predicate on the "coordinate" field.
func CoordinateHasSuffix(v string) predicate.Archive {
	return predicate.Archive(sql.FieldHasSuffix(FieldCoordinate, v))
}

// CoordinateEqualFold applies the EqualFold predicate on the "coordinate" field.
func CoordinateEqualFold(v string) predicate.Archive {
	return predicate.Archive(sql.FieldEqualFold(FieldCoordinate, v))
}

// CoordinateContainsFold applies the ContainsFold predicate on the "coordinate" field.
func CoordinateContainsFold(v string) predicate.Archive {
	return predicate.Archive(sql.FieldContainsFold(FieldCoordinate, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Archive) predicate.Archive {
	return predicate.Archive(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Archive) predicate.Archive {
	return predicate.Archive(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Archive) predicate.Archive {
	return predicate.Archive(sql.NotPredicates(p))
}
